<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Carousel slider with intro", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_carousel-slider-with-intro tm-tmp-category_sliders';
$thememountain_data['content'] = <<<CONTENT
[vc_row force_fullwidth="true" columns_on_tablet="keep" padding_top="80"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>SHOWCASE</h6>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_carousel_slider_holder visible_slides="4" tabs_id="1508258774-40" auto_advance="" show_nav_arrows="" use_pagination="true" pagination_color="#000000" transition_easing="easeInOutQuint"][tm_carousel_slider_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="1508258757-1-50c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-2.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508258930603-7c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 3" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-3.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508258941394-9c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 4" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508321738374-4"][/tm_carousel_slider_item][tm_carousel_slider_item title="slide 5" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-2.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1524084388825-10"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 6" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-3.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1526153861553-2"][/tm_carousel_slider_item][/tm_carousel_slider_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
