<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Centered slider with feature columns", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_centered-slider-with-feature-columns tm-tmp-category_content';
$thememountain_data['content'] = <<<CONTENT
[vc_row equalize="true" columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-fingerprint" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Touch ID</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-aircraft-take-off" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Arr/Dep Info</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_slider_holder slider_type="content" width="350" height="custom" height_custom="620" slider_id="slide-1525857995-75" auto_advance="true" pause_on_hover="true" show_nav_arrows="" pagination_color_1="#ffffff" pagination_color_2="#33363a" transition_easing="easeInOutCubic" transition_speed="1000"][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-1.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide 1" slide_id="slide-1525857755-1-66"][/tm_slider_item][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-2.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide 2" slide_id="1525858096508-1-6"][/tm_slider_item][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-3.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide" slide_id="1525858097509-2-8"][/tm_slider_item][/tm_slider_holder][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-ticket" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>In-App Ticketing</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-shield" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>3-Grade Encryption</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
