<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Client grid with stat", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_client-grid-with-stat tm-tmp-category_clients';
$thememountain_data['content'] = <<<CONTENT
<p>[vc_row equalize="true" columns_on_tablet="keep" use_background="yes" background_color=""][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="4/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_stats margin_bottom="0" margin_bottom_mobile="20" display_inline="false" is_boxed="false" stat_from="0" stat_to="145" stat_measure="+" description="Projects completed in 2014" stat_font_size="100px" stat_color="#33363a" border_style="" box_size="medium" background_color="" border_color="" stat_description_font_size="13px" stat_description_color="#33363a" el_id="" el_class=""][/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_clients_holder tabs_id="tabs-1503586291-24" client_name_color="rgba(51,54,58,0.6)" client_description_color="#999999"][tm_client_item title="Jorge Jense" textarea_html_bkg_color="#ffffff" tab_id="tab-1503586113-1-38"]Design Firm[/tm_client_item][tm_client_item title="Adam Tarres" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586458176-5"]Clothing Brand[/tm_client_item][tm_client_item title="Bestreet" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586495893-6"]Clothing Brand[/tm_client_item][tm_client_item title="Element " textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586507397-10"]Skateboard Co.[/tm_client_item][tm_client_item title="Cantina " textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586530213-5"]French Bistro[/tm_client_item][tm_client_item title="Macaw" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586540903-5"]Image Editing[/tm_client_item][tm_client_item title="Burlington Inc." textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586550891-4"]Development[/tm_client_item][tm_client_item title="Thanner &amp; Co" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586564447-9"]Sports Brand[/tm_client_item][tm_client_item title="Apple" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586581463-0"]Electronics[/tm_client_item][tm_client_item title="Muska Co." textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586593685-4"]Clothing Brand[/tm_client_item][tm_client_item title=" Mullener" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586608230-9"]Leather Goods[/tm_client_item][tm_client_item title="Rockabilly" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503586623356-8"]Barbershop[/tm_client_item][/tm_clients_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>

CONTENT;
vc_add_default_templates( $thememountain_data );
