<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Feature columns (2 cols)", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_feature-columns-2-cols tm-tmp-category_feature-columns';
$thememountain_data['content'] = <<<CONTENT
[vc_row equalize="true" columns_on_tablet="force_2" padding_top="60" use_background="yes" background_color="#ffffff"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/1"][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-lifebuoy" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Top Rated Support</h4>
With every purchase of Kant WordPress Theme you get 6 months included top rated support to help you get up and running. Your support licence can thereafter be extended.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-video" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Docs &amp; Video Tuts</h4>
Kant comes with detailed documentation that outlines every shortcode and how to set up your theme. In addition, we've prepared some 30+ narrated video tutorials in English.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-upload" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Frequent Updates</h4>
You are in good hands with ThemeMountain. We work hard to ensure the theme always offers you the best experience possible and take pride in always implementing the latest  technologies.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-round-brush" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Need Something Specific</h4>
Kant offers a large variety of options, but if you would need something specific or help to modify an existing element,  get in touch and we'll be happy provide you with a customisation quote.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>8 Homepage Layouts</h4>
To help you get started with your website, we&rsquo;ve provided 8 homepages, 8 heros, and some 100+ purpose-built content blocks.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-colours" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Extend Provided Layouts</h4>
Want to make a layout your own. No problem, we&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-text-document" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Templates on the Go</h4>
Speed up your workflow by inserting entire layouts into the page you are working on. Access all layouts and sections directly from our custom built-in template library.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-flow-parallel" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>From Head to Toe</h4>
Building WordPress landing pages for your web app? No problem, override global headers and footers on a per page basis to get a totally unique look for your page layout.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
