<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Fullscreen hero with bkg video, caption &amp; subscribe form", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_fullscreen-hero-with-bkg-video-caption-subscribe-form tm-tmp-category_forms';
$thememountain_data['content'] = <<<CONTENT
<p>[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="550" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item data_type="youtube_background" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-10-fs@2x.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.25)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61" video_youtube="zaPo86cfmDQ"][tm_slider_caption margin_bottom="40" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="200"]</p>
<p class="title-large"><span style="color: #ffffff">Create Amazing Product Pages</span></p>
<p>[/tm_slider_caption][tm_slider_caption margin_bottom="50" margin_bottom_mobile="10" column_width="6" column_offset="3" textarea_html_bkg_color="#666666" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="800"]</p>
<p class="lead"><span style="color: #ffffff">Build stunning looking product pages in mintues using carefully crafted content-blocks</span></p>
<p>[/tm_slider_caption][tm_slider_caption textarea_html_bkg_color="#ffffff" el_class="display-block"][tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="true" form_alignment="left" form_format="horizontal_merged" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="#33363a" button_background_color_hover="#3fb58b" button_border_color="#33363a" button_border_color_hover="#3fb58b" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="rgba(255,255,255,0.2)" form_border_color="rgba(255,255,255,0.2)" form_placeholder_color="#fff" form_focus_background_color="#fff" form_focus_border_color="#eee" form_focus_text_color="#fff" form_error_background_color="rgba(255,255,255,0.2)" form_error_border_color="#fff" form_error_text_color="#fff" response_message_text_color="#fff" hide_initial_response_message="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_slider_caption][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row]</p>

CONTENT;
vc_add_default_templates( $thememountain_data );
