<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Fullscreen hero with caption and play button", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_fullscreen-hero-with-caption-and-play-button tm-tmp-category_heros';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323" el_id="home"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="550" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-2-fs@2x-1.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.4)" overlay_background_use_gradient="true" overlay_background_gradient_end_color="rgba(0,0,0,0.5)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61" overlay_background_gradient_angle="45"][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInLeftShort" caption_animation_duration="800" caption_animation_delay="200"]
<h1 class="title-xlarge"><span style="color: #ffffff;">The Kant  </span></h1>
[/tm_slider_caption][tm_slider_icon margin_bottom="10" margin_bottom_mobile="10" icon_id="tm-entypo-icon-play" link_icon="use_lightbox" media_type="vimeo" lightbox_caption="This is a video caption" video_vimeo_id="138283432" display_inline="true" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#ffffff" icon_animation="scaleOut" icon_animation_delay="500" video_url_parameters="autoplay=1&amp;portrait=0&amp;title=0&amp;byline=0&amp;loop=1&amp;color=33363a"][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInRightShort" caption_animation_duration="800" caption_animation_delay="200"]
<h1 class="title-xlarge"><span style="color: #ffffff;">  Incubator</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" column_width="6" column_offset="3" textarea_html_bkg_color="#666666" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="900"]
<p class="lead"><span style="color: #ffffff;">Kant is the perfect toolkit for startups that need a professional way to presents their products or services.</span></p>
[/tm_slider_caption][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
