<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Hero with centered subscribe form(first,last name &amp; email)", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_hero-with-centered-subscribe-formfirstlast-name-email tm-tmp-category_forms';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="150" padding_bottom="150" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(0,0,0,0.1)" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-app-3@2x.jpg"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="false" form_alignment="left" form_format="horizontal" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe " button_background_color="#3fb58b" button_background_color_hover="#33363a" button_border_color="#3fb58b" button_border_color_hover="#33363a" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="#fff" form_border_color="#fff" form_placeholder_color="#7a7d84" form_focus_background_color="#fff" form_focus_border_color="#3fb58b" form_focus_text_color="#3fb58b" form_error_background_color="#f8f8f8" form_error_border_color="#3fb58b" form_error_text_color="#7a7d84" response_message_text_color="#fff" checkbox_radio_background_color="" checkbox_radio_border_color="" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="" response_message_text_color="" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
