<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Hero with two col pricing table", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_hero-with-two-col-pricing-table tm-tmp-category_heros';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#ffffff" add_overlay="true" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-2@2x.jpg"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_pricing_table_holder table_size="large" table_content_alignment="center" table_header_bottom_padding="0" table_price_bottom_padding="0" table_footer_bottom_padding="0" border_color="rgba(255,255,255,0.01)"][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" title_font_color="#ffffff" price_font_color="#ffffff" options_font_color="#ffffff" button_bkg_color="rgba(255,255,255,0.01)" bkg_color_hover="#3fb58b" border_color="#ffffff" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Consultation" tab_id="table-152579956543" table_price="99" table_currency="$" table_interval="single fee" table_footer_text="Select Option" link_url="#"]The Timber Commercial Team License is for up to 10 developers in the same organisation.[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="true" show_column_button="true" link_target="_self" title_font_color="#ffffff" price_font_color="#ffffff" options_font_color="#ffffff" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Market Study" tab_id="tab_id-1525799721522-0" table_price="329" table_currency="$" table_interval="single fee" table_footer_text="Select Option" link_url="#"]The Timber Commercial Team License is for up to 10 developers in the same organisation.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
