<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Single pricing table with content right", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_single-pricing-table-with-content-right tm-tmp-category_pricing-tables';
$thememountain_data['content'] = <<<CONTENT
[vc_row equalize="true" columns_on_tablet="keep" padding_top="120" el_id="pricing"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="4/12"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-50">Smart Simple Pricing</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_pricing_table_holder table_content_alignment="center" table_header_bottom_padding="0" table_price_bottom_padding="0" border_color="rgba(255,255,255,0.01)"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="true" show_column_button="true" link_target="_self" price_line_color="#dddddd" button_bkg_color="#3fb58b" bkg_color_hover="#33363a" border_color="#3fb58b" border_color_hover="#33363a" label_color="#ffffff" label_color_hover="#ffffff" title="Organization" tab_id="table-152595467113e82c-f4fdd138-631b" table_price="129" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Commercial Organization License is for an unlimited number of developers.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][/vc_row_inner][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="7/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h5 class="mb-20">100 Plus Blocks</h5>
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h5 class="mb-20">24/7 Premium Support</h5>
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h5 class="mb-20">78 Plus Layouts</h5>
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h5 class="mb-20">Awesome Code</h5>
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
