<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Split hero with slider left 2 (50/50)", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_split-hero-with-slider-left-2-5050 tm-tmp-category_sliders';
$thememountain_data['content'] = <<<CONTENT
<p>[vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_hero_split_slider_content_holder height="regular" tabs_id="tabs-1493888059-26" auto_advance="" show_nav_arrows="" use_pagination="true" media_alignment="left" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCubic"][tm_hero_split_slider_content_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-project-1-half@2x-1.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="slideLeftRight" tab_id="tab-1493887461-1-29"]</p>
<h3>Case Study: The Palm.</h3>
<p class="lead">When it comes to speed, Kant WordPress offers you the best experience possible.</p>
<p>We&rsquo;ve taken all the necessary steps to ensure that Kant loads faster and scores better than regular WordPress themes in tests like GTMatrix and Pingdom.</p>
<p>[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Play Presentation" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-play" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][tm_hero_split_slider_content_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-2-fs@2x-2.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" media_alignment="right" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_2" slide_animation="slideTopBottom" tab_id="tab_id-1493887855773-6"]</p>
<h3>Case Study: Home Design Inc.</h3>
<p class="lead">When buying a theme from us, you can rest assured that we will maintain it.</p>
<p>Our theme comes with 8 in-house plugins, which means that when there is an update, you&rsquo;ll be sure to always have the latest version.  We&rsquo;ve also included Visual Composer and other third-party plugins.</p>
<p>[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Purchase Kant" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-shopping-cart" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][/tm_hero_split_slider_content_holder][/vc_column][/vc_row]</p>

CONTENT;
vc_add_default_templates( $thememountain_data );
