<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Three col pricing tables", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_three-col-pricing-tables tm-tmp-category_pricing-tables';
$thememountain_data['content'] = <<<CONTENT
<p>[vc_row equalize="true" columns_on_tablet="keep" padding_top="120" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_pricing_table_holder table_content_alignment="center" table_header_bottom_padding="0" table_price_bottom_padding="0" border_color="rgba(255,255,255,0.01)"][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Startup" tab_id="table-1525954671138296-6fa3ff89-2c7e" table_price="12" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Free Commercial Developer License is for individual developers only working on a single project.[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="true" show_column_button="true" link_target="_self" button_bkg_color="#3fb58b" bkg_color_hover="#33363a" border_color="#3fb58b" border_color_hover="#33363a" label_color="#ffffff" label_color_hover="#ffffff" title="Small team" tab_id="tab_id-1525954942476-28296-6fa3ff89-2c7e" table_price="9" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Commercial Team License is for up to 10 developers in the same organization.[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Organization" tab_id="tab_id-1526030695833-4" table_price="15" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Commercial Organization License is for an unlimited number of developers.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column][/vc_row]</p>

CONTENT;
vc_add_default_templates( $thememountain_data );
