<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Thumbnail grid", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_thumbnail-grid tm-tmp-category_images';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" extra_space_top="110" extra_space_bottom="80" push_section="#image-set-2" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-1-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-2-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-3-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
