<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Two col pricing table with info left", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_sections_templates tm-tmp_two-col-pricing-table-with-info-left tm-tmp-category_pricing-tables';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Get A Quote</h3>
<p class="lead">Two simple plans to help you get started and get a quote. All plans can be tailored to suit your company&rsquo;s needs.</p>
[/tm_textblock][tm_button link_to="modal" button_label="Questions About Pricing? Contact us" modal_target="3949" button_size="medium"][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="8/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Consulation" tab_id="tab_id-1502199065398-18414-39a8a570-01b59c54-f47365d3-d1e3" table_price="Free" table_interval="7 days a week"]Have a project in mind but need help defining the goals. Our team will gladly take a look and provide you with a free quote.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15" tabs_id="1523357854112-0-4"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Market Study" tab_id="1523357854152-0-59c54-f47365d3-d1e3" table_price="1500" table_currency="$" table_interval="starter price"]Are you in the startup stage and need a professional opinion on project goals. We'll give you a full market study at a competitive price.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
