<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "About Style Four", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_about-style-four tm-tmp-category_about-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row equalize="true" columns_on_tablet="force_2" padding_bottom="0" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h1 class="title-large">Hi I'm John</h1>
<p class="lead">Kant is a powerful multi-layout and multi-purpose WordPress theme.</p>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="7/12"][tm_image margin_bottom="0" margin_bottom_mobile="0" image_id="8052" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep" padding_bottom="110" use_background="yes" background_color="#3fb58b"][vc_column h_text_align="left" h_text_align_mobile="center-on-mobile" v_align="v-align-top" column_offset="" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#3fb58b"]
<h3 class="mb-mobile-40"><span style="color: #ffffff">Here are some awesome brands and people that I've worked with in the past.</span></h3>
<span style="color: #ffffff">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </span>

[/tm_textblock][tm_button margin_bottom="0" margin_bottom_mobile="40" icon_id="tm-entypo-icon-download" button_label="Download Full List" button_size="medium" bkg_color="rgba(0,0,0,0.01)" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#ffffff" label_color_hover="#3fb58b"][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="7/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_logos logo_type="3" border_bkg_color_hover="rgba(255,255,255,0.2)" logo_bkg_color_hover="rgba(10,10,10,0.1)" logos_id="6582,6583,6584,6585,6586,6587,6588,6589,6590"][/tm_logos][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="7" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-mobile-40">I've worked for some great companies before working for ThemeMountain, here's a brief.</h3>
Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.

[/tm_textblock][tm_button margin_bottom="0" margin_bottom_mobile="40" icon_id="tm-entypo-icon-download" button_label="Download Full List" button_size="medium"][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="5" width="7/12"][tm_timeline_holder slider_id="fullscreen-1526148322-1" dot_bkg_color="#3fb58b" dot_border_color="#3fb58b" line_bkg_color="#eeeeee" date_color="#3fb58b" title="Experience"][tm_timeline_item textarea_html_bkg_color="#ffffff" title="2010" tab_id="1526148321893-3"]
<h4>Front-end Developer Danone</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_timeline_item][tm_timeline_item textarea_html_bkg_color="#ffffff" title="2015" tab_id="tab_id-1526148629847-7"]
<h4>Front-end Developer Nike</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_timeline_item][tm_timeline_item textarea_html_bkg_color="#ffffff" title="2016" tab_id="tab_id-1526148657679-3"]
<h4>Front-end Developer Danone</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_timeline_item][tm_timeline_item textarea_html_bkg_color="#ffffff" title="2018" tab_id="tab_id-1526148757096-4"]
<h4>Front-end Developer ThemeMountain</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_timeline_item][/tm_timeline_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="50" padding_bottom="40" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-facebook-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="" label_color_hover="#3fb58b"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-twitter-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="" label_color_hover="#3fb58b"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-linkedin-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="" label_color_hover="#3fb58b"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-skype-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="" label_color_hover="#3fb58b"][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
