<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Accordions", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_accordions tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Accordions are a great way for presenting information in a limited amount of space. Accordions can be altered in size and allow for multiple open panels.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]

<hr />

[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Default Accordion</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_accordion_holder accordion_border_style="rounded" use_icon="" header_background_color_active="#3fb58b" header_border_color_active="#3fb58b" header_text_color_active="#ffffff" accordion_id="4e364e8a-3969-4"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 1" accordion_id="1489177332-74"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Section 2" accordion_id="1489177332-34"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="60" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Multiple Open Panels</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_accordion_holder toggle_multiple="true" accordion_border_style="rounded" use_icon="" header_background_color_active="#3fb58b" header_border_color_active="#3fb58b" header_text_color_active="#ffffff" accordion_id="4bed24fe-50e8-9"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 1" accordion_id="1489177399-70"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 2" accordion_id="1489177399-27"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="60" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>With icons</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_accordion_holder accordion_border_style="rounded" use_icon="true" header_background_color_active="#3fb58b" header_border_color_active="#3fb58b" header_text_color_active="#ffffff" accordion_id="dbaa3634-cec6-7"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 1" accordion_id="9da883b6-cae1-0"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Section 2" accordion_id="4dc4550c-cf5c-2"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="60" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Accordion Style 2</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_accordion_holder accordion_style="bordered" accordion_border_style="rounded" use_icon="true" header_border_color_active="#3fb58b" header_text_color_active="#3fb58b" accordion_id="aed7626d-f201-2"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 1" accordion_id="8d589faa-fd26-0"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Section 2" accordion_id="b960be88-d53f-4"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="60" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Accordion Style 3</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_accordion_holder accordion_style="line" use_icon="true" header_border_color_active="#3fb58b" header_text_color_active="#3fb58b" accordion_id="bbb6a17b-fe70-10"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Section 1" accordion_id="ae0dca4e-9553-5"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Section 2" accordion_id="683ee177-13c1-1"]
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
Accordions are a great way for presenting information in a limited amount of space. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
