<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Backgroudn Video PRoject", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_backgroudn-video-project tm-tmp-category_project-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="400" slider_id="slide-1508258666-6" auto_advance="" show_nav_arrows="true" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item data_type="vimeo_background" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/vimeo-fallback-image-1.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.1)" pagination_color_palette="nav_color_1" title="Slide" slide_id="slide-1508258180-1-24" video_vimeo="58449984"][tm_slider_caption textarea_html_bkg_color="#999999" caption_animation="scaleIn"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">Background Video</span></h1>
[/tm_slider_caption][tm_slider_icon icon_id="tm-entypo-icon-down-open-mini" link_icon="scroll_to_section" link_url="#brief" display_inline="true" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#3fb58b" icon_animation="slideInUpShort" icon_animation_delay="400"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" el_id="brief"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4 class="mb-30">THE BRIEF</h4>
[/tm_textblock][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="text-xlarge">Avalanche slider now supports html5, YouTube and Vimeo background videos without the standard controls!</p>
[/tm_textblock][tm_divider][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Awards</h4>
<ul>
 	<li><i class="icon-default-style none accent-color"></i>Milan Design Award</li>
 	<li><i class="icon-default-style none accent-color"></i>Design Squared</li>
 	<li><i class="icon-default-style none accent-color"></i>Awwwards</li>
</ul>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>What We Did</h4>
<ul>
 	<li><i class="icon-default-style none accent-color"></i>Product Design</li>
 	<li><i class="icon-default-style none accent-color"></i>Photography</li>
 	<li><i class="icon-default-style none accent-color"></i>Web Development</li>
</ul>
[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_hero_split_slider_content_holder height="regular" tabs_id="tabs-1493888059-26" auto_advance="" show_nav_arrows="" use_pagination="true" media_alignment="left" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCubic"][tm_hero_split_slider_content_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-1@2x-2.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="slideLeftRight" tab_id="tab-1493887461-1-297273-f116c2d6-d796"]
<h2 class="mb-20">Optimised for Speed</h2>
<p class="lead">When it comes to speed, Kant WordPress offers you the best experience possible.</p>
We&rsquo;ve taken all the necessary steps to ensure that Kant loads faster and scores better than regular WordPress themes in tests like GTMatrix and Pingdom.

[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Play Presentation" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-play" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][tm_hero_split_slider_content_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-1@2x-1.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" media_alignment="right" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_2" slide_animation="slideTopBottom" tab_id="tab_id-1493887855773-67273-f116c2d6-d796"]
<h2 class="mb-20">The Trust Factor</h2>
<p class="lead">When buying a theme from us, you can rest assured that we will maintain it.</p>
Our theme comes with 8 in-house plugins, which means that when there is an update, you&rsquo;ll be sure to always have the latest version.  We&rsquo;ve also included Visual Composer and other third-party plugins.

[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Purchase Kant" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-shopping-cart" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][/tm_hero_split_slider_content_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
