<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Carousel Slider Project", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_carousel-slider-project tm-tmp-category_project-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#333333"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="400" slider_id="slide-1508258666-6" auto_advance="" show_nav_arrows="true" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-project-2-fs@2x.jpg" background_color="#333333" overlay_background_color="rgba(0,0,0,0.4)" pagination_color_palette="nav_color_1" title="Slide" slide_id="slide-1508258180-1-24"][tm_slider_caption textarea_html_bkg_color="#999999" caption_animation="scaleIn"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">Carousel Slider Project </span></h1>
[/tm_slider_caption][tm_slider_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-down-open-mini" link_icon="scroll_to_section" link_url="#brief" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#3fb58b" icon_animation="slideInUpShort" icon_animation_delay="400"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="force_1" is_section_block="yes" el_id="brief"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="title-medium">We redesigned Ctw from scratch and created an identity that was true to their core values.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6 class="mb-30">THE BRIEF</h6>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6 class="mb-30">CONCEPT</h6>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_video video_type="vimeo" video_vimeo_id="66061189" video_url_parameters="title=0&amp;byline=0&amp;portrait=0"][/tm_video][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_parallax image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-2-hero@2x.jpg" height_type="custom" parallax_id="8df6b5cb-492d-9"][tm_aux_icon icon_id="tm-entypo-icon-play" link_icon="use_lightbox" media_type="vimeo" lightbox_caption="This is a Vimeo video caption" video_vimeo_id="164320913" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#ffffff" video_url_parameters="autoplay=1"][tm_aux_caption margin_bottom="0" margin_bottom_mobile="0" textarea_html_bkg_color="#bababa"]
<h4 class="color-white"><span style="color: #ffffff">Play User Story</span></h4>
<p class="color-white"><span style="color: #ffffff">Discover why so many people opt for Traveller as their travel app.</span></p>
[/tm_aux_caption][/tm_parallax][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" padding_top="80"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>SHOWCASE</h6>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_carousel_slider_holder visible_slides="4" tabs_id="1508258774-40" auto_advance="" show_nav_arrows="" use_pagination="true" pagination_color="#000000" transition_easing="easeInOutQuint"][tm_carousel_slider_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="1508258757-1-50c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-2.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508258930603-7c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 3" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-3.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508258941394-9c850-1f36d644-fb39"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 4" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1508321738374-4"][/tm_carousel_slider_item][tm_carousel_slider_item title="slide 5" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-2.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1524084388825-10"][/tm_carousel_slider_item][tm_carousel_slider_item title="Slide 6" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-3.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type="" tab_id="tab_id-1526153861553-2"][/tm_carousel_slider_item][/tm_carousel_slider_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
