<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Color Swatches", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_color-swatches tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Showcase your project color palettes like a pro with the color swatch shortcode. Show or hide swatch title and/or hex value and choose between boxed, round or bordered swatches.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]

<hr />

[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" use_background="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Square</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="10/12"][tm_color_swatch_holder][tm_color_swatch_item title="Grapefruit 1" hex_reference="#ED5565" swatch_background_color="#ed5565" swatch_border_color="#ed5565" tab_id="1489179456-1-11"][/tm_color_swatch_item][tm_color_swatch_item title="Grapefruit 2" hex_reference="#DA4453" swatch_background_color="#da4453" swatch_border_color="#da4453" tab_id="tab_id-1489179691688-9"][/tm_color_swatch_item][tm_color_swatch_item title="Bittersweet 1" hex_reference="#FC6E51" swatch_background_color="#fc6e51" swatch_border_color="#fc6e51" tab_id="tab_id-1489179711409-0"][/tm_color_swatch_item][tm_color_swatch_item title="Bittersweet 2" hex_reference="#E9573F" swatch_background_color="#e9573f" swatch_border_color="#e9573f" tab_id="tab_id-1489179736754-9"][/tm_color_swatch_item][tm_color_swatch_item title="Sunflower 1" hex_reference="#FFCE54" swatch_background_color="#ffce54" swatch_border_color="#ffce54" tab_id="tab_id-1489179759793-5"][/tm_color_swatch_item][tm_color_swatch_item title="Sunflower 2" hex_reference="#FCBB42" swatch_background_color="#fcbb42" swatch_border_color="#fcbb42" tab_id="tab_id-1489179800750-2"][/tm_color_swatch_item][/tm_color_swatch_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" use_background="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Round</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="10/12"][tm_color_swatch_holder tabs_id="1489179835188-0-4"][tm_color_swatch_item title="Grass 1" hex_reference="#A0D468" swatch_style="icon-circled" swatch_background_color="#a0d468" swatch_border_color="#a0d468" tab_id="1489179835267-0-4"][/tm_color_swatch_item][tm_color_swatch_item title="Grass 2" hex_reference="#8CC152" swatch_style="icon-circled" swatch_background_color="#8cc152" swatch_border_color="#8cc152" tab_id="1489179835352-0-8"][/tm_color_swatch_item][tm_color_swatch_item title="Mint 1" hex_reference="#48CFAD" swatch_style="icon-circled" swatch_background_color="#48cfad" swatch_border_color="#48cfad" tab_id="1489179835448-0-9"][/tm_color_swatch_item][tm_color_swatch_item title="Mint 2" hex_reference="#37BC9B" swatch_style="icon-circled" swatch_background_color="#37bc9b" swatch_border_color="#37bc9b" tab_id="1489179835547-0-2"][/tm_color_swatch_item][tm_color_swatch_item title="Aqua 1" hex_reference="#4FC1E9" swatch_style="icon-circled" swatch_background_color="#4fc1e9" swatch_border_color="#4fc1e9" tab_id="1489179835667-0-1"][/tm_color_swatch_item][tm_color_swatch_item title="Aqua 2" hex_reference="#3BAFDA" swatch_style="icon-circled" swatch_background_color="#3bafda" swatch_border_color="#3bafda" tab_id="1489179835758-0-1"][/tm_color_swatch_item][/tm_color_swatch_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" use_background="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bordered</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="10/12"][tm_color_swatch_holder tabs_id="1489180087025-0-1"][tm_color_swatch_item title="Blue Jean 1" hex_reference="#5D9CEC" swatch_background_color="#ffffff" swatch_border_color="#5d9cec" swatch_icon_color="#5d9cec" tab_id="1489180087115-0-1"][/tm_color_swatch_item][tm_color_swatch_item title="Blue Jean 2" hex_reference="#4A89DC" swatch_background_color="#ffffff" swatch_border_color="#4a89dc" swatch_icon_color="#4a89dc" tab_id="1489180087205-0-2"][/tm_color_swatch_item][tm_color_swatch_item title="Lavender 1" hex_reference="#AC92EC" swatch_background_color="#ffffff" swatch_border_color="#ac92ec" swatch_icon_color="#ac92ec" tab_id="1489180087298-0-1"][/tm_color_swatch_item][tm_color_swatch_item title="Lavender 2" hex_reference="#967ADC" swatch_background_color="#ffffff" swatch_border_color="#967adc" swatch_icon_color="#967adc" tab_id="1489180087400-0-10"][/tm_color_swatch_item][tm_color_swatch_item title="Rose 1" hex_reference="#EC87C0" swatch_background_color="#ffffff" swatch_border_color="#ec87c0" swatch_icon_color="#ec87c0" tab_id="1489180087485-0-3"][/tm_color_swatch_item][tm_color_swatch_item title="Rose 2" hex_reference="#D770AD" swatch_background_color="#ffffff" swatch_border_color="#d770ad" swatch_icon_color="#d770ad" tab_id="1489180087570-0-9"][/tm_color_swatch_item][/tm_color_swatch_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
