<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Column Structure", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_column-structure tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes" el_id="intro"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Buttons can be styled in a variety of ways to achieve the look required by using a combination of size classes, background color/border-color, text color classes, border style classes and icons.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_divider border_color="#dddddd"][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="100" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Column Widths</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_size="custom" box_top_bottom_padding="60" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Full Width</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Half</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Half</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Two Thirds</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>One Third</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="3/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>One Fourth</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="9/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Three Fourth</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Five Sixths</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.aliquip ex ea commodo consequat.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="" width="2/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>One Sixth</h3>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile.[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="100" use_background="yes" background_color="#fafafa" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Column Push/Pull</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="4" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Three Fourths</h3>
Rearrange columns with ease using push and pull, regardless of the order in which they appear. This column is pushed 4 columns and will appear first on mobile.[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="" column_push="" column_pull="8" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>One Fourth</h3>
This column is pulled 8 columns and will appear last on mobile.[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="100" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Column Offset</h2>
Easily move sections up to eleven columns by using column offsets.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_size="small" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="" column_offset="" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
This column has no offset.[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_size="small" box_background_color="#9df7aa" box_background_color_hover="#9df7aa" box_border_color="#9df7aa" box_border_color_hover="#9df7aa" column_offset="4" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
This column is offset by 4 columns[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed" box_size="small" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="8" column_push="" column_pull="" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Third</h3>
This column is offset by 8 columns[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
