<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Column Animation", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_column-animation tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes" el_id="intro"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Buttons can be styled in a variety of ways to achieve the look required by using a combination of size classes, background color/border-color, text color classes, border style classes and icons.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="1/1"][tm_divider border_color="#dddddd"][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="100" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="" column_offset="2" column_push="" column_pull="" width="8/12"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Column Animations</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Fade In</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInUpShort" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Bottom - Short</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInRightShort" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Right - Short</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInDownShort" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Top - Short</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInLeftShort" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Left - Short</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInUpLong" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Bottom - Long</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInRightLong" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Right - Long</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInDownLong" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Top - Long</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInLeftLong" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Slide in Left - Long</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceIn" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce In</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceOut" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce Out</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceInUp" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce in Bottom</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceInRight" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce in Right</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceInDown" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce in Top</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="bounceInLeft" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Bounce in Left</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="scaleIn" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Scale in</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="scaleOut" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Scale out</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="flipInX" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Flip in X</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="flipInY" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Flip in Y</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="spinInX" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Spin in X</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="spinInY" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Spin in Y</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="helicopterIn" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Helicopter in</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="helicopterOut" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Helicopter out</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="signSwingTop" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Swing in Top</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="signSwingRight" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Swing in Right</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="signSwingBottom" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Swing in Bottom</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="signSwingLeft" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Swing in Left</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="wiggleX" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Wiggle X</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="wiggleY" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Wiggle Y</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="dropUp" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Drop in Bottom</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="dropDown" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Drop in Top</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="rollInLeft" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Roll in Left</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="rollInRight" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Roll in Right</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="turnInRight" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Turn in Right</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="" style="boxed" box_size="custom" box_top_bottom_padding="110" box_left_right_padding="60" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" box_border_color="#f4f4f4" box_border_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="turnInLeft" delay="200" threshold="1" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Turn in Left</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
