<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Content Slider Project", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_content-slider-project tm-tmp-category_project-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="150" use_background="yes" background_color="#33363a"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="60" padding_bottom="60"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#33363a"]
<h1 class="title-xlarge"><span style="color: #ffffff">Apple Marketing</span></h1>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#33363a"]
<p class="lead"><span style="color: #ffffff">The perfect toolkit to build your pages to precise specifications.</span></p>
<p class=""><span style="color: #ffffff">Our theme gives you access to a large variety of custom-built elements, functionalities and useful shortcodes that can be inserted into any section with just a few clicks. We&rsquo;ve also included a full template library accessible directly from Visual Composer, which means you can create full pages on the fly.</span></p>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#33363a"]<span style="color: #ffffff">When buying a theme from us, you can rest assured that we will maintain it. Our theme comes with 8 in-house plugins, which means that when there is an update, you&rsquo;ll be sure to always have the latest version. In addition, with every purchase of Kant, you get 6 months, 24/7 included premium support.</span>[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="3/12"][tm_textblock textarea_html_bkg_color="#33363a"]
<h4><span style="color: #ffffff">What We Did</span></h4>
<ul>
 	<li><span style="color: #ffffff"><i class="icon-default-style none accent-color"></i>Product Design</span></li>
 	<li><span style="color: #ffffff"><i class="icon-default-style none accent-color"></i>Photography</span></li>
 	<li><span style="color: #ffffff"><i class="icon-default-style none accent-color"></i>App Development</span></li>
</ul>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_button button_label="Download Project Brief" button_size="medium" bkg_color="#3fb58b" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#3fb58b" border_color_hover="rgba(255,255,255,0.3)" label_color="#ffffff" label_color_hover="#ffffff"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_slider_holder slider_type="content" width="1110" height="custom" height_custom="624" slider_id="slide-1508488221-49" auto_advance="" show_nav_arrows="true" transition_easing="easeInOutQuint"][tm_slider_item data_type="youtube" video_auto_play="" video_mute="" background_color="#ffffff" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_transition="slideLeftRight" title="Slide 1" slide_id="slide-1508488130-1-8" video_youtube="Kkq8a6AV3HM"][/tm_slider_item][tm_slider_item data_type="youtube" video_mute="" background_color="#000000" pagination_color_palette="nav_color_1" slide_transition="slideLeftRight" title="Slide 2" slide_id="slide-1523996437350-2-7" video_youtube="ufBLI6bB9sg"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#33363a"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="80"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#232323"]
<h2 class="mb-30"><span style="color: #ffffff">Project Overview</span></h2>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#232323"]<span style="color: #ffffff">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</span>[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-dots-three-vertical" textarea_html_bkg_color="#33363a" label_color="#ffffff" label_color_hover="#ffffff" slide_id="01314186-0f70-10"]
<h5><span style="color: #ffffff">Distribution</span></h5>
<span style="color: #ffffff">Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-video-camera" textarea_html_bkg_color="#33363a" label_color="#ffffff" label_color_hover="#ffffff" slide_id="01314186-0f70-10"]
<h5><span style="color: #ffffff">Filming</span></h5>
<span style="color: #ffffff">Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-network" textarea_html_bkg_color="#33363a" label_color="#ffffff" label_color_hover="#ffffff" slide_id="01314186-0f70-10"]
<h5><span style="color: #ffffff">Marketing</span></h5>
<span style="color: #ffffff">Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="3" column_push="" column_pull="" width="6/12"][tm_blockquote quote="I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend." cite="ADAMFOUR" size="large" alignment="center"][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
