<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Ecoomerce", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_ecoomerce tm-tmp-category_concept-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="550" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-17-fs@2x.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.5)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61"][tm_slider_caption margin_bottom="0" margin_bottom_mobile="0" textarea_html_bkg_color="#666666" hide_caption_on_mobile="true" caption_animation="slideInDownShort" caption_animation_duration="800" caption_animation_delay="500"]
<p class="lead" style="text-align: center;"><strong><span style="color: #ffffff;">WELCOME TO THE</span></strong></p>
[/tm_slider_caption][tm_slider_caption margin_bottom="0" margin_bottom_mobile="0" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="scaleIn" caption_animation_duration="800" caption_animation_delay="200"]
<p class="title-xlarge"><span style="color: #ffffff;">Kant.Boutique</span></p>
[/tm_slider_caption][tm_slider_caption margin_bottom="20" margin_bottom_mobile="20" textarea_html_bkg_color="#666666" hide_caption_on_mobile="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="500"]
<p class="lead" style="text-align: center;"><span style="color: #ffffff;">Products from American Apparel, Birkenstock &amp; more</span></p>
[/tm_slider_caption][tm_slider_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-down-open-mini" link_icon="scroll_to_section" link_url="#concept" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#3fb58b" icon_animation="scaleIn" icon_animation_delay="1000"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" clear_all_padding="yes" use_background="yes" background_color="#f9f9f9" el_id="concept"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_hero_split_slider_content_holder height="custom" height_custom="700" tabs_id="tabs-1525879362-21" auto_advance="" show_nav_arrows="true" use_pagination="true" media_alignment="left" pagination_color_1="#ffffff" pagination_color_2="#33363a" transition_easing="easeInOutCubic" transition_speed="1000"][tm_hero_split_slider_content_item title="Slide 1" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-half-4@2x.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" background_color="#f8f8f8" pagination_color_palette="nav_color_1" slide_animation="slideLeftRight" tab_id="tab-1525879298-1-88"]
<h2 class="mb-30">Concept</h2>
<p class="lead">Kant is the perfect toolkit for startups that need a professional way to presents their products or services.</p>
We only send you products that relate to your preference and previous purchases. Offers are sent out on a weekly basis. Unsubscribe at any moment.[/tm_hero_split_slider_content_item][tm_hero_split_slider_content_item title="Slide 2" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-half-2@2x-2.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" media_alignment="right" background_color="#f8f8f8" pagination_color_palette="nav_color_2" slide_animation="slideLeftRight" tab_id="tab_id-1525880344648-10"]
<h2 class="mb-30">Handcrafted</h2>
<p class="lead">We're proud of this product and we hope you'll be eqully as proud building a site with Kant.</p>
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_hero_split_slider_content_item][tm_hero_split_slider_content_item title="Slide 3" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-half-3@2x.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" background_color="#f8f8f8" pagination_color_palette="nav_color_1" slide_animation="scaleIn" tab_id="tab_id-1525880437022-3"]
<h2 class="mb-30">Accessories</h2>
<p class="lead">We're proud of this product and we hope you'll be eqully as proud building a site with Kant.</p>
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.[/tm_hero_split_slider_content_item][/tm_hero_split_slider_content_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" el_id="recent-products"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2><strong>Recently Added Products</strong></h2>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_button margin_bottom="0" margin_bottom_mobile="0" button_label="View All Products" link_url="/thememountain-kant/shop" button_size="medium"][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="right" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][products columns="3" orderby="date" order="" ids="6937, 6964, 6948, 6967, 6970, 6929, 6958, 7000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8" add_overlay="true" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/signup-4@2x.jpg"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#7c7c7c"]
<h3 class="&quot;mb-10"><span style="color: #ffffff;">Always Get The Latest</span></h3>
<span style="color: #ffffff;">Subscribe to Onboard and get the latest notifications and updates. We take spamming seriously.</span>

[tm_content_mailchimp_form hide_name_field="true" hide_lastname_field="true" form_alignment="left" form_format="stacked" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="#33363a" button_background_color_hover="#3fb58b" button_border_color="#33363a" button_border_color_hover="#3fb58b" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="rgba(255,255,255,0.2)" form_border_color="rgba(255,255,255,0.2)" form_placeholder_color="#fff" form_focus_background_color="#fff" form_focus_border_color="#eee" form_focus_text_color="#fff" form_error_background_color="rgba(255,255,255,0.2)" form_error_border_color="#fff" form_error_text_color="#fff" checkbox_radio_background_color="rgba(255,255,255,0.2)" checkbox_radio_border_color="rgba(255,255,255,0.2)" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="" response_message_text_color="#fff" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="3" column_push="" column_pull="" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2 style="text-align: center;">Here's why people trust Kant</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1503587853-17" use_auto_advance="" pagination_color="#33363a"][tm_testimonials_item title="Supersuz - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" tab_id="tab-1503587805-1-18"]
<p style="text-align: center;">This is the second time I&rsquo;ve used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome&hellip; I will continue to use Theme Mountain for future projects.</p>
[/tm_testimonials_item][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503587974072-2"]
<p style="text-align: center;">Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.</p>
[/tm_testimonials_item][tm_testimonials_item title=" Boica812 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503588031952-0"]
<p style="text-align: center;">It is a marvelous product &hellip; but the flash customer support tops it all &hellip; HIGHLY RECOMMENDED! 5* product and service</p>
[/tm_testimonials_item][tm_testimonials_item title="Adamfor - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" tab_id="tab_id-1503588145711-10"]
<p style="text-align: center;">I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.</p>
[/tm_testimonials_item][/tm_testimonials_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" use_background="yes" background_color="#f9f9f9"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_logos items_per_row="5" logo_type="2" bkg_color_logo="#ffffff" bkg_color_logo_hover="#f8f8f8" logos_id="6153,6156,6158,6155,6157,6152,7034,6442,6151,6154"][/tm_logos][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#ffffff"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_hero_5 height="custom" height_custom="600" media_content_type="map" textarea_html_bkg_color="#ffffff" media_alignment="right" text_color="" overlay_background_color="rgba(0,0,0,0.01)" map_style="greyscale" zoom_level="11" map_coordinates_1="40.723301,-74.002988" map_info_1="Store Location 1 - New York City" map_marker_1="7741" map_coordinates_2="40.723301,-73.907888" map_info_2="Store Location 2 - New York City" map_marker_2="7741"]
<h2 class="mb-40" style="text-align: left;">Visit Our Stores!</h2>
<p class="lead" style="text-align: left;"><span class="font-alt-1">Find special in-store starting today.</span></p>
<p class="mb-0" style="text-align: left;">With every purchase of a ThemeMountain product you get 6 months premium support! We provide our customers with friendly, timely, and carefully detailed support. For any pre-sale questions, please contact us through our profile.</p>
[/tm_hero_5][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
