<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Feature Columns", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_feature-columns tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Use feature columns to highlight key information of one or multiple sections. Featured columns can be aligned, left, center, right and further styled using icons and boxes.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]

<hr />

[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="force_2"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" slide_id="f69fe512-3a24-7"]
<h4>4 Mobile App Layouts</h4>
To help you get started with your web app landing or homepage, we&rsquo;ve provided 4 variations of the web app concept, including a one-page demo as well.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-colours" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Extend Provided Layouts</h4>
Want to make a layout your own. No problem, we&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-flow-parallel" textarea_html_bkg_color="#ffffff" slide_id="f69fe512-3a24-7"]
<h4>From Head to Toe</h4>
Building WordPress landing pages for your web app? No problem, override global headers and footers on a per page basis to get a totally unique look for your page layout.[/tm_feature_columns][/vc_column][/vc_row][vc_row columns_on_tablet="force_2" use_background="yes" background_color="#f4f4f4"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-play" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h3>Extend Provided Layouts</h3>
Want to make a layout your own. We've prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" box_shadow="true" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-note" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h3>4 Web App Layouts</h3>
To help you get started with your web app landing or homepage, we've provided 4 variations of the web app concept, including a one-page demo as well.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#f4f4f4" box_background_color_hover="#f4f4f4" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-list" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h3>Templates On The Go</h3>
Speed up your workflow by inserting layouts into the page you're working on. Access layouts and sections from our custom built-in template library.[/tm_feature_columns][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="force_2"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" use_background="yes" background_color="#ffffff" add_overlay="yes" overlay_background_color="rgba(63,181,139,0.7)" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-31-portrait.jpg" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" box_text_color="rgba(255,255,255,0.7)" box_text_color_hover="rgba(255,255,255,0.7)" box_shadow="true" column_offset="" column_push="" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="5/12"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/08/logo.png" image_width="150" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Kant is a multipurpose Wordpress theme with a focus on creative agencies and freelancers.</p>
[/tm_textblock][tm_button margin_bottom="0" margin_bottom_mobile="0" button_label="Discover More" button_size="medium" border_style="rounded"][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="7/12"][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>4 Mobile App Layouts</h4>
To help you get started with your web app landing or homepage, we&rsquo;ve provided 4 variations of the web app concept, including a one-page demo as well.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-colours" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Extend Provided Layouts</h4>
Want to make a layout your own. No problem, we&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-text-document" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Templates on the Go</h4>
Speed up your workflow by inserting entire layouts into the page you are working on. Access all layouts and sections directly from our custom built-in template library.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-flow-parallel" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>From Head to Toe</h4>
Building WordPress landing pages for your web app? No problem, override global headers and footers on a per page basis to get a totally unique look for your page layout.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f4f4f4"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 style="text-align: center">Animated Featured Columns</h3>
<p style="text-align: center">Use one of our 30+ animations to animate columns as they enter into view.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner equalize="true" columns_on_tablet="force_2" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="flipInY" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-check" icon_margin_bottom="40" icon_margin_bottom_mobile="40" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="e71ca5ac-d3fb-4"]
<h3>Optimised for Speed</h3>
<p class="mb-mobile-30">We&rsquo;ve taken the necessary steps to ensure Kant loads fast &amp; scores high in tests like GTMatrix and Pingdom.</p>
[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#3fb58b" box_background_color_hover="#3fb58b" box_border_color="#3fb58b" box_border_color_hover="#3fb58b" box_text_color="#ffffff" box_text_color_hover="#ffffff" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="flipInX" delay="400" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-check" icon_margin_bottom="40" icon_margin_bottom_mobile="40" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#ffffff" label_color_hover="#666666" slide_id="611a9dda-d4b6-3"]
<h3>Versatile</h3>
<p class="mb-mobile-30">Kant can be easily adapted to any project you may have, from a design studio to a mobile app and travel agencies.</p>
[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="flipInY" delay="800" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-check" icon_margin_bottom="40" icon_margin_bottom_mobile="40" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#666666" label_color_hover="#666666" slide_id="145d5cf4-de16-3"]
<h3>Docs &amp; Video Tuts</h3>
<p class="mb-mobile-30">With every purchase of Kant you get access to extensive documentation as well as narrated, hi-resolution video tutorials</p>
[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#fafafa"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" icon_style="icon-circled" bkg_color="#fafafa" bkg_color_hover="#fafafa" border_color="#3fb58b" border_color_hover="#3fb58b" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h5>4 MOBILE APP LAYOUTS</h5>
To help you get started with your web app landing or homepage, we&rsquo;ve provided 4 variations of the web app concept, including a one-page demo as well.[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-crop" textarea_html_bkg_color="#ffffff" icon_style="icon-circled" bkg_color="#fafafa" bkg_color_hover="#fafafa" border_color="#3fb58b" border_color_hover="#3fb58b" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h5> TEMPLATES ON THE GO</h5>
Speed up your workflow by inserting entire layouts into the page you are working on. Access all layouts and sections directly from our custom built-in template library.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-colours" textarea_html_bkg_color="#ffffff" icon_style="icon-circled" bkg_color="#fafafa" bkg_color_hover="#fafafa" border_color="#3fb58b" border_color_hover="#3fb58b" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h5>EXTEND PROVIDED LAYOUTS</h5>
Want to make a layout your own. No problem, we&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.
<h3></h3>
[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-flow-parallel" textarea_html_bkg_color="#ffffff" icon_style="icon-circled" bkg_color="#fafafa" bkg_color_hover="#fafafa" border_color="#3fb58b" border_color_hover="#3fb58b" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="9af2d690-efa5-5"]
<h5>FROM HEAD TO TOE</h5>
Building WordPress landing pages for your web app? No problem, override global headers and footers on a per page basis to get a totally unique look for your page layout.[/tm_feature_columns][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
