<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Grid Project", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_grid-project tm-tmp-category_project-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#333333"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="400" slider_id="slide-1508258666-6" auto_advance="" show_nav_arrows="true" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/slide-project-3@2x.jpg" background_color="#333333" overlay_background_color="rgba(0,0,0,0.4)" pagination_color_palette="nav_color_1" title="Slide" slide_id="slide-1508258180-1-24"][tm_slider_caption textarea_html_bkg_color="#999999" caption_animation="scaleIn"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">Lithography</span></h1>
[/tm_slider_caption][tm_slider_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-down-open-mini" link_icon="scroll_to_section" link_url="#brief" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#3fb58b" icon_animation="slideInUpShort" icon_animation_delay="400"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4 class="mb-30">The Brief</h4>
<strong>Client</strong>: Lithography
<strong>Date</strong>: June 12, 2014
<strong>Type</strong>: Art Direction, Design
<strong>Site</strong>: www.clientsite.com[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead mb-50">We rebuilt and revived a company identity that had lost touch with its target market.</p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" slider_id="slide-1526214272-45" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCubic" parallax=""][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-3-1-1.jpg" background_color="#ffffff" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide 1" slide_id="slide-1526214208-1-16"][/tm_slider_item][tm_slider_item data_type="vimeo" pagination_color_palette="nav_color_1" slide_transition="slideLeftRight" title="Slide 2" slide_id="slide-1526214334282-1-9" video_vimeo="103318844" el_id="&amp;title=0&amp;byline=0&amp;portrait=0&amp;color=3fb58b"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead text-large color-theme mb-50">The invention of the printing press was one of the most important events in human history.</p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes" use_background="yes" background_color="#f9f9f9"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_grid show_filter_menu="" show_project_title_and_description="false" grid_items="size:10|order_by:date|post_type:tm_folio|tax_query:131" width="full_width" fixed_thumb_dimensions="true" set_as_background_images="true" column_number="4" column_gutters="none" link_color="#666666" link_color_hover="#000000" rollover_bkg_color="rgba(0,0,0,0.3)" project_title_color="#ffffff" project_description_color="#ffffff"][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="3" column_push="" column_pull="" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2 style="text-align: center">Here's why users
love Onboard</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1503587853-1771c8-43823b5d-8b35" use_auto_advance="" pagination_color="#33363a"][tm_testimonials_item title="Supersuz - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar.jpg" tab_id="tab-1503587805-1-1871c8-43823b5d-8b35"]
<p style="text-align: center">This is the second time I&rsquo;ve used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome&hellip; I will continue to use Theme Mountain for future projects.</p>
[/tm_testimonials_item][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/bio-avatar.jpg" tab_id="tab_id-1503587974072-271c8-43823b5d-8b35"]
<p style="text-align: center">Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.</p>
[/tm_testimonials_item][tm_testimonials_item title=" Boica812 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-3.jpg" tab_id="tab_id-1503588031952-071c8-43823b5d-8b35"]
<p style="text-align: center">It is a marvelous product &hellip; but the flash customer support tops it all &hellip; HIGHLY RECOMMENDED! 5* product and service</p>
[/tm_testimonials_item][tm_testimonials_item title="Adamfor - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-2.jpg" tab_id="tab_id-1503588145711-1071c8-43823b5d-8b35"]
<p style="text-align: center">I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.</p>
[/tm_testimonials_item][/tm_testimonials_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
