<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Landing Page", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_landing-page tm-tmp-category_landing-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="550" slider_id="slide-1490904265-24" auto_advance="" show_nav_arrows="" use_pagination="" pagination_color_1="#ffffff" pagination_color_2="#000000" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item data_type="youtube_background" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-23-fs@2x.jpg" background_color="#232323" overlay_background_color="rgba(10,10,10,0.2)" pagination_color_palette="nav_color_1" title="Slide" slide_id="slide-1490904254-1-94" video_youtube="fROUjfwNkUI"][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="700"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">K</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="1000"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">a</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="300"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">n</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="200"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">t </span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">W</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="700"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">o</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="400"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">r</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="1000"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">d</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="1200"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">P</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="500"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">r</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="300"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">e</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="400"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">s</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="700"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">s</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="700"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff"> T</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="1000"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">h</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="500"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">e</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="700"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">m</span></h1>
[/tm_slider_caption][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#999999" display_inline="true" caption_animation="scaleIn" caption_animation_delay="500"]
<h1 class="title-xlarge" style="text-align: center"><span style="color: #ffffff">e</span></h1>
[/tm_slider_caption][tm_slider_caption textarea_html_bkg_color="#999999" caption_animation="scaleOut" caption_animation_delay="1100"]
<p class="lead" style="text-align: center"><span style="color: #ffffff">To help you get started and build something beautiful</span></p>
[/tm_slider_caption][tm_slider_button margin_bottom="0" margin_bottom_mobile="0" link_to="scroll" button_label="Discover the Demos" link_url="#demos" scroll_offset="0" display_inline="true" button_size="large" bkg_color="#33363a" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#33363a" border_color_hover="#ffffff" label_color="#ffffff" label_color_hover="#ffffff" button_animation="slideInLeftShort" button_animation_delay="1300"][tm_slider_button margin_bottom="0" margin_bottom_mobile="0" link_to="scroll" button_label="Discover the Features" link_url="#features" scroll_offset="0" display_inline="true" button_size="large" bkg_color="#3fb58b" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#3fb58b" border_color_hover="#ffffff" label_color="#ffffff" label_color_hover="#ffffff" button_animation="slideInRightShort" button_animation_delay="1300"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="150"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>About <span class="font-alt-1">Kant</span></h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Kant is an elegant, versatile, multi-purpose theme that gives you the tools you need to express who you are and what your business does in a professional and coherent manner.  To help you get started with your website we've made sure to include 8 core concepts, 8 heros, and some 100+ content blocks that you can use to tailor Kant to your needs and preferences.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="110" use_background="yes" background_color="#202020" el_id="demos"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#232323"]
<h3><span style="color: #ffffff">Concepts</span></h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_grid show_filter_menu="" show_project_title_and_description="true" grid_items="size:40|order_by:title|order:ASC|tax_query:169" force_grid_item_link_targets="_blank" layout_mode="fitRows" alignment="center" link_color="#ffffff" link_color_hover="#999999" link_color_active="#999999" rollover_bkg_color="rgba(10,10,10,0.2)" project_title_color="#ffffff" project_description_color="#eaeaea" rollover_animation="overlay-fade-in" rollover_easing="easeInOutCubic"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="110" use_background="yes" background_color="#202020" el_id="heros"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#232323"]
<h3><span style="color: #ffffff">Special Heros</span></h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_grid show_filter_menu="" show_project_title_and_description="false" grid_items="size:40|order_by:title|order:ASC|tax_query:170" force_grid_item_link_targets="_blank" layout_mode="fitRows" alignment="center" link_color="#ffffff" link_color_hover="#999999" link_color_active="#999999" rollover_bkg_color="rgba(10,10,10,0.2)" project_title_color="#ffffff" project_description_color="#eaeaea" rollover_animation="overlay-fade-in" rollover_easing="easeInOutCubic"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/feature-images-1.jpg" textarea_html_bkg_color="#ffffff" media_alignment="right" media_animation="slideInLeftShort" media_animation_threshold="0.3" slide_id="9a33354c-47e8-0"]
<h2 class="mb-30">Hit the Ground Running with Our OneClick Concepts</h2>
<p class="lead">With our OneClick Concept Importer, chose your concept, click import and start customizing.</p>
Each concept can be imported separately and comes with portfolio pages, blog pages, and common pages.  Extend any concept using our template library and insert additional sections.[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="80"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/feature-images-2.jpg" textarea_html_bkg_color="#ffffff" media_animation="slideInRightShort" slide_id="9a33354c-47e8-0"]
<h2 class="mb-30">Build Faster with Our Template Library</h2>
<p class="lead">Build truly stunning layouts quickly using purpose-built content blocks. Simple!</p>
Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/feature-images-3.jpg" textarea_html_bkg_color="#232323" media_alignment="right" media_animation="slideInLeftShort" slide_id="9a33354c-47e8-0"]
<h2 class="mb-30"><span style="color: #ffffff">Customise Kant WordPress to Your Liking</span></h2>
<p class="lead"><span style="color: #999999">Kant offers you the possibility to create custom headers and footer for any page.</span></p>
<span style="color: #999999">This is useful for when you need to create unique concepts that require a completely different approach to navigation, content, and footers. Build an unlimited number of menus and custom footers to suit your needs.  </span>[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="80" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/feature-images-4.jpg" textarea_html_bkg_color="#232323" content_animation="fadeIn" media_animation="slideInRightShort" slide_id="9a33354c-47e8-0"]
<h2 class="mb-30"><span style="color: #ffffff">Showcase Your Work with Stunning Grids</span></h2>
<p class="lead"><span style="color: #999999">Build amazing grids on the fly to showcase your designs, photography or products.</span></p>
<span style="color: #999999">There is no limit the number of grids you can build. Modify grid layouts, rollovers, animations, tile ratios and margins individually for every grid. </span>[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f4f4f4"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Optimised for Speed</h2>
<p class="lead">We&rsquo;ve taken all the necessary steps to ensure that Kant loads faster and scores better than regular WordPress themes in tests like PageSpeed, YSlow and Pingdom.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_2" padding_top="0" padding_bottom="20"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="yes" background_color="#ffffff" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/page-speed.jpg" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#eeeeee" box_border_color_hover="#eeeeee" column_offset="2" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInLeftShort" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>PageSpeed Score</h4>
<p class="title-large"><span class="font-alt-1"><strong>94%</strong></span></p>
[/tm_textblock][tm_button button_label="Check the Report" link_url="https://gtmetrix.com/reports/wp.thememountain.com/kdkUYA2p" link_target="_blank" display_inline="true" button_size="medium" border_color="#ffffff" border_color_hover="#2d66f7" label_color="#ffffff"][/vc_column_inner][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" use_background="yes" background_color="#ffffff" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/yslow-1.jpg" style="boxed_round" box_size="xlarge" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#eeeeee" box_border_color_hover="#eeeeee" column_offset="" column_push="" column_pull="" column_animation="animation_on_scroll" animation="slideInRightShort" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>YSlow Score</h4>
<p class="title-large"><span class="font-alt-1"><strong>90%</strong></span></p>
[/tm_textblock][tm_button button_label="Check the Report" link_url="https://gtmetrix.com/reports/wp.thememountain.com/kdkUYA2p" link_target="_blank" display_inline="true" button_size="medium" border_color="#ffffff" border_color_hover="#2d66f7" label_color="#ffffff"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0" use_background="yes" background_color="#ffffff"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Extensive Theme Features</h2>
[/tm_textblock][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="force_2" padding_top="60" use_background="yes" background_color="#ffffff"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/1"][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-lifebuoy" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Top Rated Support</h4>
With every purchase of Kant WordPress Theme you get 6 months included top rated support to help you get up and running. Your support licence can thereafter be extended.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-video" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Docs &amp; Video Tuts</h4>
Kant comes with detailed documentation that outlines every shortcode and how to set up your theme. In addition, we've prepared some 30+ narrated video tutorials in English.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-upload" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Frequent Updates</h4>
You are in good hands with ThemeMountain. We work hard to ensure the theme always offers you the best experience possible and take pride in always implementing the latest  technologies.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-round-brush" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Need Something Specific</h4>
Kant offers a large variety of options, but if you would need something specific or help to modify an existing element,  get in touch and we'll be happy provide you with a customisation quote.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>8 Homepage Layouts</h4>
To help you get started with your website, we&rsquo;ve provided 8 homepages, 8 heros, and some 100+ purpose-built content blocks.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-colours" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Extend Provided Layouts</h4>
Want to make a layout your own. No problem, we&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_1" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-text-document" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>Templates on the Go</h4>
Speed up your workflow by inserting entire layouts into the page you are working on. Access all layouts and sections directly from our custom built-in template library.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_feature_columns icon_id="tm-entypo-icon-flow-parallel" textarea_html_bkg_color="#ffffff" label_color="#666666" label_color_hover="#666666" slide_id="f69fe512-3a24-7"]
<h4>From Head to Toe</h4>
Building WordPress landing pages for your web app? No problem, override global headers and footers on a per page basis to get a totally unique look for your page layout.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="150" padding_bottom="120" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(45,102,247,0.7)" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/slide-4-fs@2x.jpg" use_overlay_background_color="true"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="70"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#999999"]
<h2><span style="color: #ffffff">Start Creating with Kant Today</span></h2>
<p class="lead"><span style="color: #ffffff">With every purchase you get 6 months included premium support</span></p>
[/tm_textblock][tm_button margin_bottom="inherit" button_label="Start Browsing Kant" link_url="/thememountain-kant/creative-agency/" display_inline="true" button_size="large" bkg_color="rgba(255,255,255,0.01)" bkg_color_hover="#2d66f7" border_color="#ffffff" border_color_hover="#2d66f7" label_color="#ffffff" label_color_hover="#ffffff"][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="force_2" set_font_color="yes" font_color="#ffffff" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-lifebuoy" textarea_html_bkg_color="#ffffff" label_color="#ffffff" label_color_hover="#ffffff" slide_id="f69fe512-3a24-7"]
<h4>Premium Support</h4>
With every purchase of Kant WordPress theme you get 6 months access to our premium support to help you get up and running. You can easily extend your support once the 6 month period is over.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-documents" textarea_html_bkg_color="#ffffff" label_color="#ffffff" label_color_hover="#ffffff" slide_id="f69fe512-3a24-7"]
<h4>Extensive Documentation</h4>
With every purchase of Kant you get access to extensive documentation that covers every shortcode that comes with the theme as well as a detailed guide on posts, portfolio, and custom post types.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-video-camera" textarea_html_bkg_color="#ffffff" label_color="#ffffff" label_color_hover="#ffffff" slide_id="f69fe512-3a24-7"]
<h4>30+ Video Tutorials</h4>
In addition to extensive documentation and premium support, you have access to thirty plus carefully narrated tutorial videos that walk you through all the key aspects of the theme.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
