<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Logo Slider", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_logo-slider tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Avalanche is a responsive, CSS3 transitions driven slider with a simple JS fallback for older browsers. It supports images, HTML5 backgorund video, YouTube and Vimeo videos, and a range of 3D transitions for captions and caption images.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="0" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Logo Slider</h3>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_logo_slider_holder visible_slides="5" tabs_id="1507298447-22" auto_advance="" use_pagination="true" transition_easing="easeInOutQuint"][tm_logo_slider_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/meat-logo-grid-1.svg" tab_id="1507293855-1-0"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/air-logo-grid.svg" tab_id="tab_id-1507298474532-1"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 3" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/designus-logo-grid.svg" tab_id="tab_id-1507298483959-5"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 4" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/techy-logo-grid.svg" tab_id="tab_id-1507298496616-4"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 5" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/sawards-logo-grey-grid.svg" tab_id="tab_id-1507298506968-7"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 6" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/rosco-logo-grid.svg" tab_id="tab_id-1507298520050-5"][/tm_logo_slider_item][tm_logo_slider_item title="Slide 7" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/repetition-logo-grid.svg" tab_id="tab_id-1524654005102-3"][/tm_logo_slider_item][/tm_logo_slider_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
