<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Mobile Application", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_mobile-application tm-tmp-category_concept-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_bottom="0" use_background="yes" background_color="#33363a"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="80" padding_bottom="50"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#33363a"]
<h1 class="title-large"><span style="color: #ffffff;">Kant Le Voyageur</span></h1>
<p class="lead">Build a professional App landing page</p>
[/tm_textblock][tm_button icon_id="tm-entypo-icon-app-store" button_type="app" button_label="AppStore" link_url="#" display_inline="true" button_size="medium" bkg_color="#ffffff" bkg_color_hover="#3fb58b" border_color="#ffffff" border_color_hover="#3fb58b" label_color="#33363a" label_color_hover="#ffffff" button_sub_label="Download On The"][tm_button icon_id="tm-entypo-icon-google-play" button_type="app" button_label="GooglePlay" link_url="#" display_inline="true" button_size="medium" bkg_color="#ffffff" bkg_color_hover="#3fb58b" border_color="#ffffff" border_color_hover="#3fb58b" label_color="#33363a" label_color_hover="#ffffff" button_sub_label="Download On"][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" column_animation="parallax_on_scroll" parallax_speed="0.15" width="1/1"][tm_image margin_bottom="0" margin_bottom_mobile="0" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-1.png" image_width="400" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Here's How</h2>
[/tm_textblock][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">With a dedicated team and highly tailored services we ensure a calculated result each and every time. Have questions relating to the process, just get in touch with us.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-list" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Find A Trip</h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-ticket" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Save Boardingpass</h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-aircraft-take-off" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Check-in &amp; Fly</h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="1/1"][tm_parallax image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-app-1@2x-1.jpg" use_fade="" text_color="#ffffff" parallax_id="3f14c684-01fb-5"][tm_aux_icon icon_id="tm-entypo-icon-play" link_icon="use_lightbox" media_type="vimeo" lightbox_caption="This is a Vimeo video, but you can also use YouTube or other videos" video_vimeo_id="214051739" icon_style="icon-circled" bkg_color="rgba(255,255,255,0.01)" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#ffffff" label_color_hover="#33363a" content_animation="scaleOut" video_url_parameters="autoplay=1"][tm_aux_caption textarea_html_bkg_color="#ffffff" content_animation="scaleIn"]
<h3 class="lead title-medium mb-30">Why Choose Onboard.</h3>
With over one million users OnBoard is the fastest growing community traveling app in the AppStore. Download today and start traveling like a boss![/tm_aux_caption][/tm_parallax][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-fingerprint" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Touch ID</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-aircraft-take-off" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>Arr/Dep Info</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_slider_holder slider_type="content" width="350" height="custom" height_custom="620" slider_id="slide-1525857995-75" auto_advance="true" pause_on_hover="true" show_nav_arrows="" pagination_color_1="#ffffff" pagination_color_2="#33363a" transition_easing="easeInOutCubic" transition_speed="1000"][tm_slider_item image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-1.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide 1" slide_id="slide-1525857755-1-66"][/tm_slider_item][tm_slider_item image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-2.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide 2" slide_id="1525858096508-1-6"][/tm_slider_item][tm_slider_item image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-3.png" background_color="#ffffff" overlay_background_color="" pagination_color_palette="nav_color_2" slide_transition="slideLeftRight" title="Slide" slide_id="1525858097509-2-8"][/tm_slider_item][/tm_slider_holder][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-ticket" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>In-App Ticketing</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][tm_feature_columns icon_id="tm-entypo-icon-shield" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h5>3-Grade Encryption</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/signup-2@2x.jpg"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="5/12"][tm_textblock textarea_html_bkg_color="#7c7c7c"]
<h3 class="&quot;mb-10"><span style="color: #ffffff;">Always Get The Latest</span></h3>
<span style="color: #ffffff;">Subscribe to Onboard and get the latest notifications and updates. We take spamming seriously.</span>

[tm_content_mailchimp_form hide_name_field="true" hide_lastname_field="true" form_alignment="left" form_format="stacked" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="#33363a" button_background_color_hover="#3fb58b" button_border_color="#33363a" button_border_color_hover="#3fb58b" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="rgba(255,255,255,0.2)" form_border_color="rgba(255,255,255,0.2)" form_placeholder_color="#fff" form_focus_background_color="#fff" form_focus_border_color="#eee" form_focus_text_color="#fff" form_error_background_color="rgba(255,255,255,0.2)" form_error_border_color="#fff" form_error_text_color="#fff" checkbox_radio_background_color="rgba(255,255,255,0.2)" checkbox_radio_border_color="rgba(255,255,255,0.2)" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="#fff" response_message_text_color="#fff" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" use_background="yes" background_color="#ffffff"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="3" column_push="" column_pull="" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2 style="text-align: center;">Here's why users
love Onboard</h2>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1503587853-17" use_auto_advance="" pagination_color="#33363a"][tm_testimonials_item title="Supersuz - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar.jpg" tab_id="tab-1503587805-1-18"]
<p style="text-align: center;">This is the second time I&rsquo;ve used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome&hellip; I will continue to use Theme Mountain for future projects.</p>
[/tm_testimonials_item][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/bio-avatar.jpg" tab_id="tab_id-1503587974072-2"]
<p style="text-align: center;">Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.</p>
[/tm_testimonials_item][tm_testimonials_item title=" Boica812 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-3.jpg" tab_id="tab_id-1503588031952-0"]
<p style="text-align: center;">It is a marvelous product &hellip; but the flash customer support tops it all &hellip; HIGHLY RECOMMENDED! 5* product and service</p>
[/tm_testimonials_item][tm_testimonials_item title="Adamfor - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-2.jpg" tab_id="tab_id-1503588145711-10"]
<p style="text-align: center;">I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.</p>
[/tm_testimonials_item][/tm_testimonials_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="40" padding_bottom="40" use_background="yes" background_color="#f4f4f4"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_logos items_per_row="5" logos_id="6443,6445,6157,7788,7787"][/tm_logos][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
