<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Modals", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_modals tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Modals are a great way of showing key information. You can use all our shortcodes in our modals, including subscribe and contact forms. Below are some standard modals we have prepared for you.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Cookie Modal" modal_target="2883" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Newsletter 1 Modal" modal_target="3894" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Newsletter 2 Modal" modal_target="3908" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Newsletter 3 Modal" modal_target="3899" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Newsletter 4 Modal" modal_target="3904" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Newsletter 5 Modal" modal_target="3906" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Terms Modal" modal_target="3918" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="FAQ Modal" modal_target="3921" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Contact Form Modal 1" modal_target="3963" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Contact Form Modal 2" modal_target="3949" display_inline="true" button_size="large"][tm_button margin_bottom="10" margin_bottom_mobile="10" link_to="modal" button_label="Booking Modal 1" modal_target="3966" display_inline="true" button_size="large"][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
