<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Product Two", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_product-two tm-tmp-category_concept-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="regular" minimum_height="550" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-5-page-intro@2x-1.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.25)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61"][tm_slider_caption margin_bottom="40" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="200"]
<p class="title-large"><span style="color: #ffffff;">Create Amazing Product Pages</span></p>
[/tm_slider_caption][tm_slider_caption margin_bottom="50" margin_bottom_mobile="10" column_width="6" column_offset="3" textarea_html_bkg_color="#666666" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="800"]
<p class="lead"><span style="color: #ffffff;">Build stunning looking product pages in mintues using carefully crafted content-blocks</span></p>
[/tm_slider_caption][tm_slider_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-down" link_icon="scroll_to_section" link_url="#brief" label_color="#ffffff" label_color_hover="rgba(255,255,255,0.5)" icon_animation="slideInUpShort" icon_animation_delay="1100"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" el_id="brief"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/feature-1-product-2.jpg" textarea_html_bkg_color="#ffffff" slide_id="3ac286ad-2a3d-9"]
<h3>Increase Productivity</h3>
<p class="lead">Kant is an elegant multi-purpose template that is big, bold and beautiful.</p>
<p class="mb-50">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8" el_id="brief"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_feature_sections image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/feature-1-product-2.jpg" textarea_html_bkg_color="#ffffff" media_alignment="right" slide_id="3ac286ad-2a3d-9"]
<h3>Increase Productivity</h3>
<p class="lead">Kant is an elegant multi-purpose template that is big, bold and beautiful.</p>
<p class="mb-50">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
[/tm_feature_sections][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_video video_type="vimeo" video_vimeo_id="66061189" video_url_parameters="title=0∓byline=0&amp;portrait=0"][/tm_video][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-copy" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h4>100 Plus Blocks</h4>
<h5><span style="color: #999999;">TO 300M</span></h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-browser" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h4>70+ Layouts</h4>
<h5><span style="color: #999999;">2 LEVEL SECURITY</span></h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_feature_columns icon_id="tm-entypo-icon-chat" textarea_html_bkg_color="#ffffff" icon_alignment="center" label_color="#3fb58b" label_color_hover="#3fb58b" slide_id="01314186-0f70-10"]
<h4>6 Months Support</h4>
<h5><span style="color: #999999;">ON A DAILY BASIS</span></h5>
Use feature columns to highlight key information of one or multiple sections. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/tm_feature_columns][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="40"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-40">What User's Are Saying</h3>
<p class="lead">We've been lucky enough to work with some of the best companies in the world, and we'd love for you to join the list.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1503587853-174f08-4d38cbe3-19e2" use_auto_advance="" pagination_color="#33363a"][tm_testimonials_item title="Supersuz - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab-1503587805-1-184f08-4d38cbe3-19e2"]
<p style="text-align: center;">This is the second time I&rsquo;ve used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome&hellip; I will continue to use Theme Mountain for future projects.</p>
[/tm_testimonials_item][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/bio-avatar.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503587974072-24f08-4d38cbe3-19e2"]
<p style="text-align: center;">Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.</p>
[/tm_testimonials_item][tm_testimonials_item title=" Boica812 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-3.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503588031952-04f08-4d38cbe3-19e2"]
<p style="text-align: center;">It is a marvelous product &hellip; but the flash customer support tops it all &hellip; HIGHLY RECOMMENDED! 5* product and service</p>
[/tm_testimonials_item][tm_testimonials_item title="Adamfor - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-2.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503588145711-104f08-4d38cbe3-19e2"]
<p style="text-align: center;">I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.</p>
[/tm_testimonials_item][/tm_testimonials_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="40" padding_bottom="40"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_logos items_per_row="6" logos_id="6443,6445,7993,6157,7788,7787"][/tm_logos][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="150" padding_bottom="150" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(0,0,0,0.1)" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/signup-5@2x.jpg"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="custom" box_top_bottom_padding="40" box_left_right_padding="50" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="&quot;mb-10">Always Get The Latest</h3>
Subscribe to Onboard and get the latest notifications and updates. We take spamming seriously.

[tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="true" form_alignment="left" form_format="horizontal_merged" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="" button_background_color_hover="" button_border_color="" button_border_color_hover="" button_label_color="" button_label_color_hover="" form_background_color=" form_border_color="" form_placeholder_color="" form_focus_background_color="" form_focus_border_color="" form_focus_text_color="" form_error_background_color="" form_error_border_color="" form_error_text_color="" checkbox_radio_background_color="" checkbox_radio_border_color="" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="" response_message_text_color="" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
