<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Product Three", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_product-three tm-tmp-category_concept-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="600" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item data_type="youtube_background" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-10-fs@2x.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.25)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61" video_youtube="zaPo86cfmDQ"][tm_slider_caption margin_bottom="20" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="200"]
<p class="title-large"><span style="color: #ffffff;">Create Amazing Product Pages</span></p>
[/tm_slider_caption][tm_slider_caption margin_bottom_mobile="10" column_width="6" column_offset="3" textarea_html_bkg_color="#666666" hide_caption_on_mobile="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="800"]
<p class="lead"><span style="color: #ffffff;">Build stunning looking product pages in mintues using carefully crafted content-blocks</span></p>
[/tm_slider_caption][tm_slider_caption column_width="10" column_offset="1" textarea_html_bkg_color="#ffffff" el_class="display-block"][tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="true" form_alignment="left" form_format="horizontal_merged" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="#33363a" button_background_color_hover="#3fb58b" button_border_color="#33363a" button_border_color_hover="#3fb58b" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="rgba(255,255,255,0.2)" form_border_color="rgba(255,255,255,0.2)" form_placeholder_color="#fff" form_focus_background_color="#fff" form_focus_border_color="#eee" form_focus_text_color="#fff" form_error_background_color="rgba(255,255,255,0.2)" form_error_border_color="#fff" form_error_text_color="#fff" checkbox_radio_background_color="rgba(255,255,255,0.2)" checkbox_radio_border_color="rgba(255,255,255,0.2)" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="#fff" response_message_text_color="#fff" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_slider_caption][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="40" padding_bottom="40" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_logos items_per_row="5" logos_id="7789,7788,7787,7993,6445"][/tm_logos][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>A TEMPLATE THAT SUITS YOU</h6>
All content blocks are designed to work well together no matter the order they are placed in. The combinations and possibilities are endless. Give it a try today!.

<strong class="color-theme">@smashingmag</strong>
Simply Awesome - Signed up and tested it right away. Super satisfied!

<strong class="color-theme">@techcrunch</strong>
An amazing product, install at this moment![/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_video video_type="vimeo" video_vimeo_id="161570867" video_url_parameters="title=0∓byline=0&amp;portrait=0"][/tm_video][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" style="boxed_round" box_size="custom" box_top_bottom_padding="50" box_left_right_padding="50" box_background_color="#ffffff" box_background_color_hover="#ffffff" box_border_color="#ffffff" box_border_color_hover="#ffffff" box_shadow="true" column_offset="" column_push="" column_pull="" width="6/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-10">Subscribe To Newsletter</h3>
We only use your email for sending you offers.

[tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="true" form_alignment="left" form_format="stacked" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe" button_background_color="" button_background_color_hover="" button_border_color="" button_border_color_hover="" button_label_color="" button_label_color_hover="" form_background_color="" form_border_color="" form_placeholder_color="" form_focus_background_color="" form_focus_border_color="" form_focus_text_color="" form_error_background_color="" form_error_border_color="" form_error_text_color=""form_error_background_color="rgba(255,255,255,0.2)" form_error_border_color="" form_error_text_color="" checkbox_radio_background_color="" checkbox_radio_border_color="" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="" response_message_text_color="" hide_initial_response_message="false" button_width="false" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Our subscribe forms integrate seamlessly with MailChimp, all you need is your email, list Id and API key.</p>

<h6>EMAIL SETUP</h6>
Quisque molestie elementum quam molestie malesuada. In sagittis urna vitae blandit molestie. Nam aliquet dui neque.
<h6>PRINT DESIGN</h6>
Quisque molestie elementum quam molestie malesuada. In sagittis urna vitae blandit molestie. Nam aliquet dui neque.[/tm_textblock][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep" use_background="yes" background_color="" add_overlay="true" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-product-3-1@2x.jpg"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#939393"]
<h2 class="mb-10"><span style="color: #ffffff;">Simple Pricing Options</span></h2>
<p class="lead"><span style="color: #ffffff;">From small single man teams to large organizations.</span></p>
[/tm_textblock][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep" padding_top="120" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_pricing_table_holder table_content_alignment="center" table_header_bottom_padding="0" table_price_bottom_padding="0" border_color="rgba(255,255,255,0.01)"][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Startup" tab_id="table-1525954671138296-6fa3ff89-2c7e" table_price="12" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Free Commercial Developer License is for individual developers only working on a single project.[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="true" show_column_button="true" link_target="_self" button_bkg_color="#3fb58b" bkg_color_hover="#33363a" border_color="#3fb58b" border_color_hover="#33363a" label_color="#ffffff" label_color_hover="#ffffff" title="Small team" tab_id="tab_id-1525954942476-28296-6fa3ff89-2c7e" table_price="9" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Commercial Team License is for up to 10 developers in the same organization.[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Organization" tab_id="tab_id-1526030695833-4" table_price="15" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]The Timber Commercial Organization License is for an unlimited number of developers.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Have some pre-sale questions?</h2>
<p class="mb-50">With every purchase of a ThemeMountain product you get 6 months premium support! We provide our customers with friendly, timely, and carefully detailed support. For any pre-sale questions, please contact us through our profile.</p>
[/tm_textblock][tm_button margin_bottom="0" margin_bottom_mobile="0" link_to="modal" icon_id="tm-entypo-icon-chat" button_label="Get in touch today!" modal_target="3949" button_size="medium"][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_image margin_bottom="0" margin_bottom_mobile="0" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-product-3.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
