<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Progress Bars", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_progress-bars tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Create elegant progress bars to show key information or data. Style them easily with a range of color, background, and border color classes.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]

<hr />

[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Default Bars</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Photoshop" percentage="80" measure="%" hide_measure="true" animate="true" size="medium" border_style="" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Illustrator" percentage="40" measure="%" hide_measure="true" animate="true" size="medium" border_style="" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="inDesign" percentage="67" measure="%" hide_measure="true" animate="true" size="medium" border_style="" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>With Percentage</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Photoshop" percentage="80" measure="%" hide_measure="false" animate="true" size="medium" border_style="" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Illustrator" percentage="40" measure="%" hide_measure="false" animate="true" size="medium" border_style="" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="inDesign" percentage="67" measure="%" hide_measure="false" animate="true" size="medium" border_style="" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Rounded Bars</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Photoshop" percentage="80" measure="%" hide_measure="false" animate="true" size="medium" border_style="rounded" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Illustrator" percentage="40" measure="%" hide_measure="false" animate="true" size="medium" border_style="rounded" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="inDesign" percentage="67" measure="%" hide_measure="false" animate="true" size="medium" border_style="rounded" track_background_color="#f4f4f4" track_border_color="#f4f4f4" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Pill Bars</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Photoshop" percentage="80" measure="%" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Illustrator" percentage="40" measure="%" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="inDesign" percentage="67" measure="%" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#fff" track_border_color="#fff" bar_background_color="#3fb58b" bar_border_color="#3fb58b" text_color="" el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="110" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Customised Bars</h3>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Photoshop" percentage="80" measure="/100" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#fafafa" track_border_color="#fafafa" bar_background_color="#f72d61" bar_border_color="#f72d61" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="Illustrator" percentage="40" measure="" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#eee" track_border_color="#eee" bar_background_color="#34e0a9" bar_border_color="#34e0a9" text_color="" el_id="" el_class=""][tm_content_progress_bar margin_bottom="30" margin_bottom_mobile="30" label="inDesign" percentage="67" measure=" percent" hide_measure="false" animate="true" size="medium" border_style="pill" track_background_color="#eee" track_border_color="#eee" bar_background_color="#d623eb" bar_border_color="#d623eb" text_color="" el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
