<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Rollovers", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_rollovers tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Our themes offer 14 different rollovers. These are available for image links, video links, and our portfolio grids. Set overlay &amp; caption color, caption position, animation duration &amp; easing.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]

<hr />

[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="20" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-5-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Fade In</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-33-landscape-1.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-fade-out" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Fade Out</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-17-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="img-scale-in" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Image Scale In</h6>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="20" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-7-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-fade-img-scale-in" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Fade, Image Scale In</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-15-landscape-large.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-fade-img-scale-out" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Fade, Image Scale Out</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-6-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-slide-in-top" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Slide In Top</h6>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="20" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-34-landscape-1.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-slide-in-left" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Slide In Left</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-11-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-slide-in-right" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Slide In Right</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-35-landscape-1.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-slide-in-bottom" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay Slide In Bottom</h6>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="20" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-18-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="#232323" caption_text_color="#ffffff" rollover_animation="overlay-img-slide-up" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay &amp; Image Slide Up</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/blog-4-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="#232323" caption_text_color="#ffffff" rollover_animation="overlay-img-slide-left" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay &amp; Image Slide Left</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/project-30-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="#232323" caption_text_color="#ffffff" rollover_animation="overlay-img-slide-right" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay &amp; Image Slide Right</h6>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="110" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-14-landscape-large.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="#232323" caption_text_color="#ffffff" rollover_animation="overlay-img-slide-down" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay &amp; Image Slide Down</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-25-landscape.jpg" link_image="use_lightbox" lightbox_toolbar_zoom_button="true" lightbox_toolbar_share_buttons="true" textarea_html_bkg_color="#ffffff" caption_type="rollover_caption" rollover_bkg_color="rgba(0,0,0,0.5)" caption_text_color="#ffffff" rollover_animation="overlay-img-scale-in" rollover_easing="easeInOutCubic" lightbox_caption="This is a caption"]Rollover Caption[/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h6>Overlay &amp; Image Scale In</h6>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/3"][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
