<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Services Style Two", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_services-style-two tm-tmp-category_service-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" use_background="yes" background_color="#232323"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_slider_holder slider_type="full_width" height="window_height" minimum_height="400" slider_id="slide-1502195317-59" auto_advance="" show_nav_arrows="true" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc" parallax="true" parallax_fade_on_scroll="true"][tm_slider_item image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/slide-1-fs@2x-1.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.25)" pagination_color_palette="nav_color_2" slide_transition="scaleOut" title="Slide 1" slide_id="slide-1502195278-1-61"][tm_slider_caption margin_bottom="10" margin_bottom_mobile="10" textarea_html_bkg_color="#666666" display_inline="true" caption_animation="slideInUpShort" caption_animation_duration="800" caption_animation_delay="200"]
<p class="title-xlarge" style="text-align: center"><span style="color: #ffffff">What We Offer</span></p>
[/tm_slider_caption][tm_slider_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-down-open-mini" link_icon="scroll_to_section" link_url="#intro" icon_size="small" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="#ffffff" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#3fb58b" icon_animation="slideInUpShort" icon_animation_delay="1100"][/tm_slider_item][/tm_slider_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8" el_id="intro"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="30"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">We design identities, build websites, create web and mobile applications, illustrate and create typography.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_stats_holder tabs_id="tabs-1522747052-49" is_boxed="true" border_style="rounded" box_size="large" background_color="#33363a" border_color="#33363a"][tm_stats_item title="Startups" stat_from="1110" stat_to="1234" stat_measure="+" description="Active startups at Kant" use_second_row="" stat_font_size="50px" stat_color="#ffffff" stat_description_color="#ffffff" tab_id="tab-1505388294-1-56d230-4e1a88be-d77b47b7-24055458-f269"][/tm_stats_item][tm_stats_item title="Funding" stat_from="244" stat_to="350" stat_measure="K" description="Average startup funding" use_second_row="" stat_font_size="50px" stat_color="#ffffff" stat_description_color="#ffffff" tab_id="tab_id-1505389351309-6d230-4e1a88be-d77b47b7-24055458-f269"][/tm_stats_item][tm_stats_item title="Awards" stat_from="365" stat_to="645" stat_measure="K" description="Mentions on social media" use_second_row="" stat_font_size="50px" stat_color="#ffffff" stat_description_color="#ffffff" tab_id="tab_id-1505389424670-5d230-4e1a88be-d77b47b7-24055458-f269"][/tm_stats_item][/tm_stats_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_hero_5 height="auto" media_content_type="image" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-half-2@2x-5.jpg" media_column_link="icon" link_to="lightbox" icon_id="tm-entypo-icon-play" lightbox_media_type="vimeo" lightbox_caption="This is a lightbox caption" lightbox_video_vimeo_id="81676731" textarea_html_bkg_color="#ffffff" text_color="" overlay_background_color="rgba(0,0,0,0.01)" icon_style="icon-circled" icon_label_color="#ffffff" icon_label_color_hover="#33363a" icon_bkg_color="rgba(255,255,255,0.01)" icon_bkg_color_hover="#ffffff" icon_border_color="#ffffff" icon_border_color_hover="#ffffff" media_animation="slideInRightLong" content_animation="turnInRight" lightbox_video_url_parameters="autoplay=1"]
<h3 class="mb-30">Development</h3>
<p class="mb-50">Morbi nec ultrices tellus. Fusce id est quis orci faucibus congue. Aliquam erat volutpat. Phasellus tortor velit, ornare at ullamcorper at. Ut enim ad minim veniam.</p>

<h5>Mobile Applications</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
<h5>Website Development</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.[/tm_hero_5][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_hero_5 height="auto" media_content_type="image" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-half-1@2x.jpg" textarea_html_bkg_color="#ffffff" media_alignment="right" text_color="" overlay_background_color="rgba(0,0,0,0.01)" media_animation="slideInRightLong" content_animation="turnInRight"]
<h3 class="mb-30">Design &amp; Ilustration</h3>
<p class="mb-50">Morbi nec ultrices tellus. Fusce id est quis orci faucibus congue. Aliquam erat volutpat. Phasellus tortor velit, ornare at ullamcorper at. Ut enim ad minim veniam.</p>

<h5>Identity</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
<h5>Typesetting</h5>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.[/tm_hero_5][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Getting Started</h3>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead"><span class="font-alt-1">Three simple plans to help you get started. All plans can be tailored to suit your company's needs.</span></p>
<p class="mb-80 mb-mobile-50">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" icon_for_options="true" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Logo Design" tab_id="tab_id-1502199065398-18414-39a8a570-01b5" table_price="795" table_currency="$" table_interval="starter price"]
<ul>
 	<li>3 Samples</li>
 	<li>2 Reworks</li>
 	<li>Delivery AI &amp; PSD files</li>
 	<li>20% off next project</li>
 	<li>$20 for additional mods</li>
</ul>
[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15" tabs_id="1523357854112-0-4"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" icon_for_options="true" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="WordPress Site" tab_id="1523357854152-0-5" table_price="1500" table_currency="$" table_interval="starter price"]
<ul>
 	<li>Free Domain</li>
 	<li>500 GB Bandwidth</li>
 	<li>6 Months Support</li>
 	<li>Free WordPress Setup</li>
 	<li>JetPack Premium($99)</li>
</ul>
[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15" tabs_id="1523358046692-0-6"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" icon_for_options="true" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Print Work" tab_id="1523358046724-0-2" table_price="350" table_currency="$" table_interval="starter price"]
<ul>
 	<li>1500 Copies</li>
 	<li>Duotone</li>
 	<li>300g Paper</li>
 	<li>2 Revisions</li>
 	<li>Delivery AI &amp; PSD files</li>
</ul>
[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="40" padding_bottom="0"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_button link_to="modal" button_label="Questions About Pricing? Contact us" modal_target="3949" button_size="medium"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
