<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Services Style Three", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_services-style-three tm-tmp-category_service-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="title-large"><span style="color: #dddddd">01</span></p>

<h4 class="mb-5">Web Design</h4>
<p class="mb-mobile-30">To help you get started we&rsquo;ve provided you with three service page variations, that you can modify and mix, or you can create your own using some of the 100+ sections that come with the theme.</p>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="title-large"><span style="color: #dddddd">02</span></p>

<h4 class="mb-5">Print</h4>
<p class="mb-mobile-30">Want to make a layout your own. We&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.</p>
[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/3"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="title-large"><span style="color: #dddddd">03</span></p>

<h4 class="mb-5">Illustration</h4>
<p class="mb-mobile-30">Speed up your workflow by inserting layouts into the page you&rsquo;re working on. Access layouts and sections from our custom built-in template library.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="150" padding_bottom="150" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(0,0,0,0.2)" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-2@2x-1.jpg"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="3" column_push="" column_pull="" width="6/12"][tm_textblock textarea_html_bkg_color="#999999"]
<h3 class="mb-30"><span style="color: #ffffff">Case Study: Home Design Inc.</span></h3>
<span style="color: #ffffff">Amazing Apparel approached us with the idea of doing a short film showcasing core values and youthful spirit of the brand.</span>

[/tm_textblock][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-play" link_icon="use_lightbox" media_type="vimeo" lightbox_caption="A video caption, you can also add YouTube and other videos to the lightbox" video_vimeo_id="138283432" icon_style="icon-circled" bkg_color="#ffffff" bkg_color_hover="rgba(255,255,255,0.01)" border_color="#ffffff" border_color_hover="#ffffff" label_color="#33363a" label_color_hover="#ffffff" video_url_parameters="autoplay=1"][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="force_1" use_background="yes" background_color="#ffffff"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="7/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-50">Common Questions</h3>
[/tm_textblock][tm_accordion_holder accordion_border_style="rounded" use_icon="" header_background_color_active="#3fb58b" header_border_color="" header_border_color_active="rgba(255,255,255,0.01)" header_text_color_active="#ffffff" accordion_id="214c468b-dda7-7"][tm_accordion_tab_item is_active="true" textarea_html_bkg_color="#ffffff" title="Q: Is Coding Skills Needed?" accordion_id="149716f4-a671-4"]<strong>A:</strong> Nope, no coding knowledge is required to build a site with Kant.

Our theme comes with 8 in-house plugins, which means that when there is an update, you&rsquo;ll be sure to always have the latest version.  We&rsquo;ve also included Visual Composer and other third-party plugins.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Q: Is Support Included?" accordion_id="1523377096-53"]<strong>A:</strong> Yes. With every purchase, you get 6 months premium support included and access to our support forum.

Each concept can be imported separately and comes with portfolio pages, blog pages, and common pages.  Extend any concept using our template library and insert additional sections.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Q: Customisation Included?" accordion_id="1523377096-3"]<strong>A:</strong> Customisation is not included in your purchase. But we&rsquo;ll be happy to take a look at your customisation request and give you a quote.

Kant comes with some 70+ page layouts that offer unique and beautifully design blocks that look great on desktop, tablet and mobile. Kant now also includes fully functional onepage layouts! The possibilities are endless.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Q: Can Custom Headers &amp; Footers Be Created?" accordion_id="ef9a00b2-29e6-0"]<strong>A:</strong> Yup, you can create custom headers and footers for any page.

Kant offers you the possibility to create custom headers and footer for any page.

This is useful for when you need to create unique concepts that require a completely different approach to navigation, content, and footers. Build an unlimited number of menus and custom footers to suit your needs.[/tm_accordion_tab_item][tm_accordion_tab_item textarea_html_bkg_color="#ffffff" title="Q: Is This The Coolest Theme On The Planet" accordion_id="5912644d-0c0e-0"]<strong>A:</strong> Yup, it just might very well be!

Build amazing grids on the fly to showcase your designs, photography or products.

There is no limit to the number of grids you can build. Modify grid layouts, rollovers, animations, tile ratios and margins individually for every grid.[/tm_accordion_tab_item][/tm_accordion_holder][/vc_column][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-top" column_offset="1" column_push="" column_pull="" width="4/12"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/team-member-1-3.jpg" image_width="300" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4 class="mb-5">Need to talk to a human?</h4>
<p class="mb-mobile-30">Want to make a layout your own. We&rsquo;ve prepared every section as a separate element that you can insert and modify using Visual Composer Page Builder.</p>
[/tm_textblock][tm_button button_label="Get in touch" button_size="medium"][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Get A Quote</h3>
<p class="lead">Two simple plans to help you get started and get a quote. All plans can be tailored to suit your company&rsquo;s needs.</p>
[/tm_textblock][tm_button link_to="modal" button_label="Questions About Pricing? Contact us" modal_target="3949" button_size="medium"][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="8/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Consulation" tab_id="tab_id-1502199065398-18414-39a8a570-01b59c54-f47365d3-d1e3" table_price="Free" table_interval="7 days a week"]Have a project in mind but need help defining the goals. Our team will gladly take a look and provide you with a free quote.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_pricing_table_holder border_style="rounded" table_header_top_padding="40" table_header_bottom_padding="10" table_price_top_padding="0" table_price_bottom_padding="0" table_footer_top_padding="0" border_color="#eeeeee" table_price_top_bottom_padding="20" pricing_table_top_padding="15" tabs_id="1523357854112-0-4"][tm_pricing_table_item show_price_line="true" display_interval_on_new_line="true" display_table_option_as="text" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="" title_background_color="#ffffff" price_background_color="#ffffff" price_font_color="#666666" price_line_color="#dddddd" options_background_color="#ffffff" footer_background_color="#ffffff" button_bkg_color="#ffffff" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" title="Market Study" tab_id="1523357854152-0-59c54-f47365d3-d1e3" table_price="1500" table_currency="$" table_interval="starter price"]Are you in the startup stage and need a professional opinion on project goals. We'll give you a full market study at a competitive price.[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
