<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Split Hero Slider", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_split-hero-slider tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Avalanche is a responsive, CSS3 transitions driven slider with a simple JS fallback for older browsers. It supports images, HTML5 backgorund video, YouTube and Vimeo videos, and a range of 3D transitions for captions and caption images.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_hero_split_slider_content_holder height="regular" tabs_id="tabs-1493888059-26" auto_advance="" show_nav_arrows="" use_pagination="true" media_alignment="left" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCubic"][tm_hero_split_slider_content_item title="Slide 1" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-1@2x-2.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="slideLeftRight" tab_id="tab-1493887461-1-29"]
<h2 class="mb-20">Optimised for Speed</h2>
<p class="lead">When it comes to speed, Kant WordPress offers you the best experience possible.</p>
We&rsquo;ve taken all the necessary steps to ensure that Kant loads faster and scores better than regular WordPress themes in tests like GTMatrix and Pingdom.

[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Play Presentation" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-play" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][tm_hero_split_slider_content_item title="Slide 2" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-1@2x-1.jpg" textarea_html_bkg_color="#ffffff" content_media_width="split_50_50" media_alignment="right" background_color="#f4f4f4" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_2" slide_animation="slideTopBottom" tab_id="tab_id-1493887855773-6"]
<h2 class="mb-20">The Trust Factor</h2>
<p class="lead">When buying a theme from us, you can rest assured that we will maintain it.</p>
Our theme comes with 8 in-house plugins, which means that when there is an update, you&rsquo;ll be sure to always have the latest version.  We&rsquo;ve also included Visual Composer and other third-party plugins.

[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="lightbox" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="This is a lightbox caption." video_vimeo_id="118640180" video_youtube_id="" video_url="" video_url_parameters="autoplay=1" scroll_offset="0" button_type="" button_sub_label="" button_label="Purchase Kant" link_url="" link_target="" modal_target="" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-shopping-cart" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_content_item][/tm_hero_split_slider_content_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_hero_split_slider_holder height="custom" height_custom="650" content_media_width="split_50_50" tabs_id="tabs-1505304105-93" auto_advance="true" pause_on_hover="" progress_bar="" show_nav_arrows="" use_pagination="true" media_alignment="right" content_alignment="left" pagination_color_1="#ffffff" pagination_color_2="#000000" transition_easing="easeInOutCirc"][tm_hero_split_slider_item title="Slide Content" is_hero_content="true" textarea_html_bkg_color="" pagination_color_palette="nav_color_1" slide_animation="fade" tab_id="tab-1505303976-1-56"]
<h2 class="mb-20">We've Got You Covered</h2>
<p class="lead">When buying a theme from us we'll do our best to help you get up and running.</p>
With every purchase of Kant you get access to extensive documentation as well as narrated, hi-resolution video tutorials. And should you need additional assistance, you get 6 months included support.

[tm_content_button margin_bottom="30" margin_bottom_mobile="30" display_inline="false" link_to="modal" media_type="vimeo" lightbox_toolbar_zoom_button="false" lightbox_toolbar_share_buttons="false" lightbox_caption="" video_vimeo_id="" video_youtube_id="" video_url="" video_url_parameters="" scroll_offset="0" button_type="" button_sub_label="" button_label="See Our Faq" link_url="" link_target="_blank" modal_target="3921" button_size="medium" border_style="" icon_alignment="left" icon_id="icon-documents" bkg_color="" bkg_color_hover="" border_color="" border_color_hover="" label_color="" label_color_hover="" drop_shadow="false" el_id="" el_class="" lightbox_animation="fade"][/tm_hero_split_slider_item][tm_hero_split_slider_item title="Slide 1" is_hero_content="no" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-2@2x.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="fade" tab_id="tab_id-1505304151309-7"][/tm_hero_split_slider_item][tm_hero_split_slider_item title="Slide 2" is_hero_content="no" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/hero-half-1@2x-3.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="scaleOut" tab_id="tab_id-1505304284139-0"][/tm_hero_split_slider_item][tm_hero_split_slider_item title="Slide 3" is_hero_content="no" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/hero-half-1@2x.jpg" background_color="#232323" overlay_background_color="rgba(0,0,0,0.01)" pagination_color_palette="nav_color_1" slide_animation="slideLeftRight" tab_id="tab_id-1505304292532-5"][/tm_hero_split_slider_item][/tm_hero_split_slider_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
