<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Sticky Columns Project", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_sticky-columns-project tm-tmp-category_project-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" is_section_block="yes" el_id="intro"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="7/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead text-xlarge color-theme mb-30">We rebuilt and revived a company identity that had lost touch with its target market; making it hip once again!</p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Details</h4>
<strong>Client</strong>: Sweatshop
<strong>Date</strong>: June 12, 2014
<strong>Type</strong>: Art Direction, Design
<strong>Site</strong>: www.clientsite.com[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" extra_space_top="110" extra_space_bottom="80" push_section="#image-set-2" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-1-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-2-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-1-3-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" is_section_block="yes" el_id="info"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" extra_space_top="110" extra_space_bottom="110" push_section="#video-section" column_offset="" column_push="" column_pull="" width="5/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>The Advertising</h3>
This section showcases the redesign process. Insert a video, a thumbnail with a video link, images, or any other shortcode of your choice.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="6/12"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Colors</h4>
[/tm_textblock][tm_color_swatch_holder swatch_list_alignment="left" tabs_id="1507911604-97"][tm_color_swatch_item title="Forrest" hex_reference="#3fb58b" swatch_style="icon-circled" swatch_background_color="#3fb58b" swatch_border_color="#3fb58b" tab_id="tab_id-1507911445342-8"][/tm_color_swatch_item][tm_color_swatch_item title="Granite Grey" hex_reference="#33363a" swatch_style="icon-circled" swatch_background_color="#33363a" swatch_border_color="#33363a" tab_id="1507911287-1-77"][/tm_color_swatch_item][tm_color_swatch_item title="White" hex_reference="#eeeeee" swatch_style="icon-circled" swatch_background_color="#eeeeee" swatch_border_color="#eeeeee" swatch_icon_color="#dddddd" tab_id="tab_id-1507911387079-4"][/tm_color_swatch_item][/tm_color_swatch_holder][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_divider][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Identity</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_textblock][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/feature-section-2-2.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type="caption_over" caption_vertical_alignment="v-align-bottom" caption_horizontal_alignment="left" caption_text_color="#ffffff"][/tm_image][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="50"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_divider][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Typography</h4>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.[/tm_textblock][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/feature-section-1-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type="caption_over" caption_vertical_alignment="v-align-bottom" caption_horizontal_alignment="left" caption_text_color="#ffffff"][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f9f9f9" is_section_block="yes" el_id="video-section"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_video video_type="vimeo" video_vimeo_id="147734113" video_url_parameters="color=3fb58b"][/tm_video][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
