<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Sticky Elements", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_sticky-elements tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" padding_bottom="50" is_section_block="yes" el_id="intro"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Using sticky elements can be a great way of telling a story as the user scrolls down the page. Use the sticky column option on the fly in any layout.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_divider border_color="#dddddd"][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" push_section=".sticky-section-2" style="boxed_round" box_background_color="#f8f8f8" box_background_color_hover="#f8f8f8" box_border_color="#f8f8f8" box_border_color_hover="#f8f8f8" box_text_color="#33363a" box_text_color_hover="#33363a" column_offset="" column_push="6" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>A Sticky Element</h3>
This box becomes stick as it reaches the header. And it's pushed out of view by the box below it.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="6" width="1/2"][tm_video video_type="vimeo" use_lightbox="lightbox_with_icon" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/09/blog-9-landscape.jpg" image_style="rounded" icon_bkg_color="rgba(238,238,238,0.01)" icon_bkg_color_hover="#2d66f7" icon_border_color="#ffffff" icon_border_color_hover="#2d66f7" icon_label_color="#ffffff" icon_label_color_hover="#ffffff" video_vimeo_id="169675730" lightbox_caption="You can add a caption to your lightbox videos"][/tm_video][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/blog-1-landscape.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="0" is_section_block="yes" el_class="sticky-section-2"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" push_section=".sticky-section-3" style="boxed_round" box_size="custom" box_top_bottom_padding="40" box_left_right_padding="40" box_background_color="#f8f8f8" box_background_color_hover="#f8f8f8" box_border_color="#f8f8f8" box_border_color_hover="#f8f8f8" box_text_color="#33363a" box_text_color_hover="#33363a" column_offset="" column_push="" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>A Sticky Element</h3>
This box becomes stick as it reaches the header. And it's pushed out of view by the box below it.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-35-landscape-1.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type=""][/tm_image][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-31-landscape.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type="caption_over" caption_vertical_alignment="v-align-bottom" caption_horizontal_alignment="left" caption_text_color="#33363a"]// This is an overlayed image caption,
positioned top left.[/tm_image][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" is_section_block="yes" el_class="sticky-section-3"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" make_column_sticky="true" extra_space_bottom="80" style="boxed_round" box_size="custom" box_top_bottom_padding="40" box_left_right_padding="40" box_background_color="#f8f8f8" box_background_color_hover="#f8f8f8" box_border_color="#f8f8f8" box_border_color_hover="#f8f8f8" box_text_color="#33363a" box_text_color_hover="#33363a" column_offset="" column_push="6" column_pull="" box_title_color="#ffffff" box_title_color_hover="#ffffff" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>A Sticky Element</h3>
This box becomes stick as it reaches the header. And it's pushed out of view by the box below it.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="6" width="1/2"][tm_video video_type="vimeo" use_lightbox="lightbox_with_icon" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-7-landscape.jpg" image_style="rounded" icon_bkg_color="rgba(238,238,238,0.01)" icon_bkg_color_hover="#2d66f7" icon_border_color="#ffffff" icon_border_color_hover="#2d66f7" icon_label_color="#ffffff" icon_label_color_hover="#ffffff" video_vimeo_id="169675730" lightbox_caption="You can add a caption to your lightbox videos"][/tm_video][tm_image image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/project-6-landscape.jpg" link_image="none" textarea_html_bkg_color="#ffffff" image_style="rounded" caption_type="caption_over" caption_vertical_alignment="v-align-top" caption_horizontal_alignment="left" caption_text_color="#33363a"]// This is an overlayed image caption, positioned bottom left.[/tm_image][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
