<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Testimonial Slider", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_testimonial-slider tm-tmp-category_element-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="80" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="lead">Avalanche is a responsive, CSS3 transitions driven slider with a simple JS fallback for older browsers. It supports images, HTML5 backgorund video, YouTube and Vimeo videos, and a range of 3D transitions for captions and caption images.</p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="0" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Testimonial Slider</h3>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder minimum_height="200" tab_id="tabs-1484851783-83" use_auto_advance="" pagination_color="#000000" transition_easing="easeInOutCubic" ignore_row="true"][tm_testimonials_item title="Adamfour" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" tab_id="tab-1484851089-1-5"]I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.[/tm_testimonials_item][tm_testimonials_item title="ChamboWambo - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" tab_id="tab_id-1484851861109-8"]Awesome theme, easy to use and great support[/tm_testimonials_item][tm_testimonials_item title="Sakimbohsin86 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" tab_id="tab_id-1484851894497-0"]Awesome template with so many options and coding is so clean. Great work team.[/tm_testimonials_item][/tm_testimonials_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="0" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Testimonial Slider with Border</h3>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder minimum_height="200" tab_id="tabs-1484851783-83" use_auto_advance="" pagination_color="#000000" transition_easing="easeInOutCubic" ignore_row="true"][tm_testimonials_item title="Adamfour" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="border" border_color="#2d66f7" tab_id="tab-1484851089-1-5"]I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.[/tm_testimonials_item][tm_testimonials_item title="ChamboWambo - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="border" border_color="#2d66f7" tab_id="tab_id-1484851861109-8"]Awesome theme, easy to use and great support[/tm_testimonials_item][tm_testimonials_item title="Sakimbohsin86 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="border" border_color="#2d66f7" tab_id="tab_id-1484851894497-0"]Awesome template with so many options and coding is so clean. Great work team.[/tm_testimonials_item][/tm_testimonials_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="20" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Testimonial Slider with Icon</h3>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="0" use_background="yes" background_color="#f4f4f4" is_section_block="yes"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder minimum_height="200" tab_id="tabs-1484851783-83" use_auto_advance="" pagination_color="#000000" transition_easing="easeInOutCubic" ignore_row="true"][tm_testimonials_item title="Adamfour" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="icon" icon_id="entypo-icon entypo-icon-sound" icon_color="#2d66f7" tab_id="tab-1484851089-1-5"]I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.[/tm_testimonials_item][tm_testimonials_item title="ChamboWambo - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="icon" icon_id="entypo-icon entypo-icon-thumbs-up" icon_color="#2d66f7" tab_id="tab_id-1484851861109-8"]Awesome theme, easy to use and great support[/tm_testimonials_item][tm_testimonials_item title="Sakimbohsin86 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="icon" icon_id="entypo-icon entypo-icon-mouse" icon_color="#2d66f7" tab_id="tab_id-1484851894497-0"]Awesome template with so many options and coding is so clean. Great work team.[/tm_testimonials_item][/tm_testimonials_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="90" padding_bottom="20" is_section_block="yes"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3>Testimonial Slider with Avatar</h3>
[/tm_textblock][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" padding_top="0"][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1502733410-31" use_auto_advance="" pagination_color="#000000"][tm_testimonials_item title="AdamFor" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/testimonial-avatar-1.jpg" alignment="center" tab_id="tab-1502733376-1-36"]I'm just starting out and it's my second theme, and I must say, it's great. Documentation quality and customer support make making great websites way easier. I highly recommend. :)[/tm_testimonials_item][tm_testimonials_item title="ChamboWambo" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/testimonial-avatar-2.jpg" alignment="center" tab_id="tab_id-1502821481845-0"]Awesome theme, easy to use and great support[/tm_testimonials_item][tm_testimonials_item title="sakibmohsin86" column_width="6" column_offset="3" textarea_html_bkg_color="#ffffff" background_color="#ffffff" type="avatar" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/04/testimonial-avatar-3.jpg" tab_id="tab_id-1507053606721-0"]Awesome template with so many options and coding is so clean. Great work team.[/tm_testimonials_item][/tm_testimonials_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(45,102,247,0.7)" image_source="image_url" image_url="https://wp.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2017/10/hero-project-4-1.jpg" use_overlay_background_color="true"][vc_column h_text_align="left" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="3/12"][tm_textblock textarea_html_bkg_color="#232323"]
<h6 class="mb-20"><span style="color: #ffffff"><strong>BUILD STUNNING TESTIMONIAL SECTIONS</strong></span></h6>
<span style="color: #ffffff">Add testimonial sliders to heros, tabs, accordions and more.</span>[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="9/12"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1505214849-41" use_auto_advance="" pagination_color="#ffffff"][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="10" column_offset="1" textarea_html_bkg_color="#ffffff" background_color="" quote_color="#ffffff" cite_color="rgba(255,255,255,0.5)" tab_id="tab-1505214601-1-25"]Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.[/tm_testimonials_item][tm_testimonials_item title="Supersuz - ThemeForest" column_width="10" column_offset="1" textarea_html_bkg_color="#ffffff" background_color="#ffffff" quote_color="#ffffff" cite_color="rgba(255,255,255,0.5)" tab_id="tab_id-1505214930648-4"]This is the second time I've used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome... I will continue to use Theme Mountain for future projects.[/tm_testimonials_item][tm_testimonials_item title="Boica812 - ThemeForest" textarea_html_bkg_color="#ffffff" background_color="#ffffff" quote_color="#ffffff" cite_color="rgba(255,255,255,0.5)" tab_id="tab_id-1507465586820-1"]It is a marvelous product ... but the flash customer support tops it all ... HIGHLY RECOMMENDED! 5* product and service[/tm_testimonials_item][/tm_testimonials_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
