<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "Web Application", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_layout_templates tm-tmp_web-application tm-tmp-category_concept-pages';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="150"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="1" column_push="" column_pull="" width="10/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h1 class="title-large">The simplest, most effective tool for small teams</h1>
<p class="lead">Take a screenshot, make a screencast or an animated gif straight from your browser and share with your team on the fly. <strong>Sign up now and get notified when we launch!</strong></p>
[/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_top="150" padding_bottom="120" use_background="yes" background_color="#ffffff" add_overlay="true" overlay_background_color="rgba(0,0,0,0.1)" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-app-3@2x.jpg"][vc_column h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"][tm_content_mailchimp_form hide_name_field="false" hide_lastname_field="false" form_alignment="left" form_format="horizontal" form_size="medium" form_corner_style="" email_field_placeholder="Email address*" fname_field_placeholder="First name*" lname_field_placeholder="Last name*" button_label="Subscribe " button_background_color="#3fb58b" button_background_color_hover="#33363a" button_border_color="#3fb58b" button_border_color_hover="#33363a" button_label_color="#fff" button_label_color_hover="#fff" form_background_color="#fff" form_border_color="#fff" form_placeholder_color="#7a7d84" form_focus_background_color="#fff" form_focus_border_color="#3fb58b" form_focus_text_color="#3fb58b" form_error_background_color="#f8f8f8" form_error_border_color="#3fb58b" form_error_text_color="#7a7d84" checkbox_radio_background_color="" checkbox_radio_border_color="" checkbox_checked_background_color="" checkbox_checked_color="" checkbox_error_border_color="" response_message_text_color="#fff" hide_initial_response_message="false" button_width="true" initial_response_message="We don't spam." el_id="" el_class=""][/tm_textblock][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][vc_row_inner columns_on_tablet="keep" padding_top="0" padding_bottom="20"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2 class="mb-30">Increasing Your Productivity</h2>
<p class="lead">Transform your team into a well oiled machine and streamline company tasks.</p>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_video video_type="vimeo" video_vimeo_id="143282979" video_url_parameters="title=0&amp;byline=0&amp;portrait=0&amp;loop=1&amp;color=3fb58b"][/tm_video][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row equalize="true" columns_on_tablet="keep" padding_top="120"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="4/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-50">Smart Simple Pricing</h3>
Aligning your product roadmap with company goals. Your product roadmap tells a story. It shows where your product is today, where it&rsquo;s headed, and how it&rsquo;s going to get there.[/tm_textblock][/vc_column][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="8/12"][tm_pricing_table_holder table_content_alignment="center" table_header_bottom_padding="0" table_price_bottom_padding="0" border_color="rgba(255,255,255,0.01)"][tm_pricing_table_item display_interval_on_new_line="true" icon_for_options="true" textarea_html_bkg_color="#ffffff" is_callout="true" show_column_button="true" link_target="_self" button_bkg_color="#3fb58b" bkg_color_hover="#33363a" border_color="#3fb58b" border_color_hover="#33363a" label_color="#ffffff" label_color_hover="#ffffff" title="Startup" tab_id="table-152595467113" table_price="12" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]
<ul>
 	<li> 30-day free trial</li>
 	<li> 5 Team Accounts</li>
 	<li><del> Custom Domain</del></li>
 	<li><del> Custom Branding</del></li>
</ul>
[/tm_pricing_table_item][tm_pricing_table_item display_interval_on_new_line="true" icon_for_options="true" textarea_html_bkg_color="#ffffff" is_callout="" show_column_button="true" link_target="_self" button_bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" title="Organization" tab_id="tab_id-1525954942476-2" table_price="85" table_currency="$" table_interval="per month" table_footer_text="See Full Details" link_url="#"]
<ul>
 	<li>30-day free trial</li>
 	<li> 25 Team Accounts</li>
 	<li> Custom Domain</li>
 	<li> Custom Branding</li>
</ul>
[/tm_pricing_table_item][/tm_pricing_table_holder][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_divider][/vc_column][/vc_row][vc_row columns_on_tablet="keep" padding_bottom="0"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="2" column_push="" column_pull="" width="8/12"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h2>Have some pre-sale questions?</h2>
<p class="mb-50">With every purchase of a ThemeMountain product you get 6 months premium support! We provide our customers with friendly, timely, and carefully detailed support. For any pre-sale questions, please contact us through our profile.</p>
[/tm_textblock][tm_button margin_bottom="0" margin_bottom_mobile="0" link_to="modal" icon_id="tm-entypo-icon-chat" button_label="Get in touch today!" modal_target="3949" button_size="medium"][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_image margin_bottom="0" margin_bottom_mobile="0" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/hero-product-4.jpg" link_image="none" textarea_html_bkg_color="#ffffff" caption_type=""][/tm_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="center" h_text_align_mobile="center-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h3 class="mb-60">Trusted By Some Great Companies</h3>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_logos items_per_row="5" logos_id="6443,6445,6157,7788,7787,6442,6444,6155,6152,6151"][/tm_logos][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row force_fullwidth="true" columns_on_tablet="keep" padding_top="0" use_background="yes" background_color="#f8f8f8"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_testimonials_holder tab_id="tabs-1503587853-17" use_auto_advance="" pagination_color="#33363a"][tm_testimonials_item title="Supersuz - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab-1503587805-1-18"]
<p style="text-align: center;">This is the second time I&rsquo;ve used this theme, and not only is stylish and beautifully responsive - but also the support is really awesome&hellip; I will continue to use Theme Mountain for future projects.</p>
[/tm_testimonials_item][tm_testimonials_item title="Marktmcewan - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/bio-avatar.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503587974072-2"]
<p style="text-align: center;">Full marks for design and development quality. Support is the best support i have received from any purchase on Themeforest.</p>
[/tm_testimonials_item][tm_testimonials_item title=" Boica812 - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-3.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503588031952-0"]
<p style="text-align: center;">It is a marvelous product &hellip; but the flash customer support tops it all &hellip; HIGHLY RECOMMENDED! 5* product and service</p>
[/tm_testimonials_item][tm_testimonials_item title="Adamfor - ThemeForest" column_width="8" column_offset="2" textarea_html_bkg_color="#ffffff" background_color="#ffffff" boxed_testimonial="true" type="avatar" image_source="image_url" image_url="https://wpdev.thememountain.com/thememountain-kant/wp-content/uploads/sites/7/2018/05/comment-avatar-2.jpg" box_background_color="#ffffff" box_border_color="#ffffff" box_border_style="rounded" tab_id="tab_id-1503588145711-10"]
<p style="text-align: center;">I&rsquo;m just starting out and it&rsquo;s my second theme, and I must say, it&rsquo;s great. Documentation quality and customer support make making great websites way easier. I highly recommend.</p>
[/tm_testimonials_item][/tm_testimonials_holder][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
