<?php
$thememountain_data = array();
$thememountain_data['name'] = esc_html__( "2 Col Footer with Button", "thememountain-kant" );
$thememountain_data['weight'] = 0;
$thememountain_data['custom_class'] = 'vc_footer_layout_templates tm-tmp_2-col-footer-with-button tm-tmp-category_two-columns';
$thememountain_data['content'] = <<<CONTENT
[vc_row columns_on_tablet="keep" padding_top="0" padding_bottom="20"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_textblock textarea_html_bkg_color="#ffffff"]
<h4>Kant.</h4>
[/tm_textblock][/vc_column_inner][/vc_row_inner][vc_row_inner columns_on_tablet="keep" clear_all_padding="yes"][vc_column_inner h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]
<p class="alignnone">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
[/tm_textblock][/vc_column_inner][vc_column_inner h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_button margin_bottom="10" margin_bottom_mobile="10" icon_id="tm-entypo-icon-chat" button_type="app" button_label="Contact Support" button_size="medium" bkg_color="#33363a" bkg_color_hover="#3fb58b" border_color="#33363a" border_color_hover="#3fb58b" label_color="#ffffff" label_color_hover="#ffffff" button_sub_label="Require Some Help"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/1"][tm_divider border_color="rgba(221,221,221,0.2)"][/vc_column][/vc_row][vc_row columns_on_tablet="keep" clear_all_padding="yes"][vc_column h_text_align="left" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" width="1/2"][tm_textblock textarea_html_bkg_color="#ffffff"]&copy; ThemeMountain. All Rights Reserved.[/tm_textblock][/vc_column][vc_column h_text_align="right" h_text_align_mobile="left-on-mobile" v_align="v-align-middle" column_offset="" column_push="" column_pull="" width="1/2"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-facebook-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="#666666" label_color_hover="#666666"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-twitter-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="#666666" label_color_hover="#666666"][tm_icon margin_bottom="0" margin_bottom_mobile="0" icon_id="tm-entypo-icon-vimeo-with-circle" link_icon="link_to_page" link_url="#" display_inline="true" label_color="#666666" label_color_hover="#666666"][/vc_column][/vc_row]
CONTENT;
vc_add_default_templates( $thememountain_data );
