<?php
namespace ThemeMountain;

/**
 *  VC preset values
 */
TM_Vc::$vc_elements_variable['easing'] = array(
	esc_html__( 'Linear', 'thememountain-plugin' ) => 'linear',
	esc_html__( 'Swing', 'thememountain-plugin' ) => 'swing',
	esc_html__( 'Ease Out Cubic', 'thememountain-plugin' ) => 'easeOutCubic',
	esc_html__( 'Ease In Out Cubic', 'thememountain-plugin' ) => 'easeInOutCubic',
	esc_html__( 'Ease In Circ', 'thememountain-plugin' ) => 'easeInCirc',
	esc_html__( 'Ease Out Circ', 'thememountain-plugin' ) => 'easeOutCirc',
	esc_html__( 'Ease In Out Circ', 'thememountain-plugin' ) => 'easeInOutCirc',
	esc_html__( 'Ease In Expo', 'thememountain-plugin' ) => 'easeInExpo',
	esc_html__( 'Ease Out Expo', 'thememountain-plugin' ) => 'easeOutExpo',
	esc_html__( 'Ease In Out Expo', 'thememountain-plugin' ) => 'easeInOutExpo',
	esc_html__( 'Ease In Quad', 'thememountain-plugin' ) => 'easeInQuad',
	esc_html__( 'Ease Out Quad', 'thememountain-plugin' ) => 'easeOutQuad',
	esc_html__( 'Ease In Out Quad', 'thememountain-plugin' ) => 'easeInOutQuad',
	esc_html__( 'Ease In Quart', 'thememountain-plugin' ) => 'easeInQuart',
	esc_html__( 'Ease Out Quart', 'thememountain-plugin' ) => 'easeOutQuart',
	esc_html__( 'Ease In Out Quart', 'thememountain-plugin' ) => 'easeInOutQuart',
	esc_html__( 'Ease In Quint', 'thememountain-plugin' ) => 'easeInQuint',
	esc_html__( 'Ease Out Quint', 'thememountain-plugin' ) => 'easeOutQuint',
	esc_html__( 'Ease In Out Quint', 'thememountain-plugin' ) => 'easeInOutQuint',
	esc_html__( 'Ease In Sine', 'thememountain-plugin' ) => 'easeInSine',
	esc_html__( 'Ease Out Sine', 'thememountain-plugin' ) => 'easeOutSine',
	esc_html__( 'Ease In Out Sine', 'thememountain-plugin' ) => 'easeInOutSine',
	esc_html__( 'Ease In Back', 'thememountain-plugin' ) => 'easeInBack',
	esc_html__( 'Ease Out Back', 'thememountain-plugin' ) => 'easeOutBack',
	esc_html__( 'Ease In Out Back', 'thememountain-plugin' ) => 'easeInOutBack',
	);

TM_Vc::$vc_elements_variable['animation'] = array(
	esc_html__( 'No animation effects', 'thememountain-plugin' ) => '',
	esc_html__( 'Fade in', 'thememountain-plugin' ) => 'fadeIn',
	esc_html__( 'Slide in from bottom short', 'thememountain-plugin' ) => 'slideInUpShort',
	esc_html__( 'Slide in from right short', 'thememountain-plugin' ) => 'slideInRightShort',
	esc_html__( 'Slide in from top short', 'thememountain-plugin' ) => 'slideInDownShort',
	esc_html__( 'Slide in from left short', 'thememountain-plugin' ) => 'slideInLeftShort',
	esc_html__( 'Slide in from bottom long', 'thememountain-plugin' ) => 'slideInUpLong',
	esc_html__( 'Slide in from right long', 'thememountain-plugin' ) => 'slideInRightLong',
	esc_html__( 'Slide in from top long', 'thememountain-plugin' ) => 'slideInDownLong',
	esc_html__( 'Slide in from left long', 'thememountain-plugin' ) => 'slideInLeftLong',
	esc_html__( 'Bounce in', 'thememountain-plugin' ) => 'bounceIn',
	esc_html__( 'Bounce out', 'thememountain-plugin' ) => 'bounceOut',
	esc_html__( 'Bounce in from bottom', 'thememountain-plugin' ) => 'bounceInUp',
	esc_html__( 'Bounce in from right', 'thememountain-plugin' ) => 'bounceInRight',
	esc_html__( 'Bounce in from top', 'thememountain-plugin' ) => 'bounceInDown',
	esc_html__( 'Bounce in from left', 'thememountain-plugin' ) => 'bounceInLeft',
	esc_html__( 'Scale in', 'thememountain-plugin' ) => 'scaleIn',
	esc_html__( 'Scale out', 'thememountain-plugin' ) => 'scaleOut',
	esc_html__( 'Flip in X', 'thememountain-plugin' ) => 'flipInX',
	esc_html__( 'Flip in Y', 'thememountain-plugin' ) => 'flipInY',
	esc_html__( 'Spin in X', 'thememountain-plugin' ) => 'spinInX',
	esc_html__( 'Spin in Y', 'thememountain-plugin' ) => 'spinInY',
	esc_html__( 'Helicopter in', 'thememountain-plugin' ) => 'helicopterIn',
	esc_html__( 'Helicopter out', 'thememountain-plugin' ) => 'helicopterOut',
	esc_html__( 'Sign swing in from top', 'thememountain-plugin' ) => 'signSwingTop',
	esc_html__( 'Sign swing in from right', 'thememountain-plugin' ) => 'signSwingRight',
	esc_html__( 'Sign swing in from bottom', 'thememountain-plugin' ) => 'signSwingBottom',
	esc_html__( 'Sign swing in from left', 'thememountain-plugin' ) => 'signSwingLeft',
	esc_html__( 'Wiggle X', 'thememountain-plugin' ) => 'wiggleX',
	esc_html__( 'Wiggle Y', 'thememountain-plugin' ) => 'wiggleY',
	esc_html__( 'Drop in from bottom', 'thememountain-plugin' ) => 'dropUp',
	esc_html__( 'Drop in from top', 'thememountain-plugin' ) => 'dropDown',
	esc_html__( 'Roll in from left', 'thememountain-plugin' ) => 'rollInLeft',
	esc_html__( 'Roll in from right', 'thememountain-plugin' ) => 'rollInRight',
	esc_html__( 'Turn in from right', 'thememountain-plugin' ) => 'turnInRight',
	esc_html__( 'Turn in from left', 'thememountain-plugin' ) => 'turnInLeft',
	);

TM_Vc::$vc_elements_variable['animation_withtout_none'] = array(
	esc_html__( 'Fade in', 'thememountain-plugin' ) => 'fadeIn',
	esc_html__( 'Slide in from bottom short', 'thememountain-plugin' ) => 'slideInUpShort',
	esc_html__( 'Slide in from right short', 'thememountain-plugin' ) => 'slideInRightShort',
	esc_html__( 'Slide in from top short', 'thememountain-plugin' ) => 'slideInDownShort',
	esc_html__( 'Slide in from left short', 'thememountain-plugin' ) => 'slideInLeftShort',
	esc_html__( 'Slide in from bottom long', 'thememountain-plugin' ) => 'slideInUpLong',
	esc_html__( 'Slide in from right long', 'thememountain-plugin' ) => 'slideInRightLong',
	esc_html__( 'Slide in from top long', 'thememountain-plugin' ) => 'slideInDownLong',
	esc_html__( 'Slide in from left long', 'thememountain-plugin' ) => 'slideInLeftLong',
	esc_html__( 'Bounce in', 'thememountain-plugin' ) => 'bounceIn',
	esc_html__( 'Bounce out', 'thememountain-plugin' ) => 'bounceOut',
	esc_html__( 'Bounce in from bottom', 'thememountain-plugin' ) => 'bounceInUp',
	esc_html__( 'Bounce in from right', 'thememountain-plugin' ) => 'bounceInRight',
	esc_html__( 'Bounce in from top', 'thememountain-plugin' ) => 'bounceInDown',
	esc_html__( 'Bounce in from left', 'thememountain-plugin' ) => 'bounceInLeft',
	esc_html__( 'Scale in', 'thememountain-plugin' ) => 'scaleIn',
	esc_html__( 'Scale out', 'thememountain-plugin' ) => 'scaleOut',
	esc_html__( 'Flip in X', 'thememountain-plugin' ) => 'flipInX',
	esc_html__( 'Flip in Y', 'thememountain-plugin' ) => 'flipInY',
	esc_html__( 'Spin in X', 'thememountain-plugin' ) => 'spinInX',
	esc_html__( 'Spin in Y', 'thememountain-plugin' ) => 'spinInY',
	esc_html__( 'Helicopter in', 'thememountain-plugin' ) => 'helicopterIn',
	esc_html__( 'Helicopter out', 'thememountain-plugin' ) => 'helicopterOut',
	esc_html__( 'Sign swing in from top', 'thememountain-plugin' ) => 'signSwingTop',
	esc_html__( 'Sign swing in from right', 'thememountain-plugin' ) => 'signSwingRight',
	esc_html__( 'Sign swing in from bottom', 'thememountain-plugin' ) => 'signSwingBottom',
	esc_html__( 'Sign swing in from left', 'thememountain-plugin' ) => 'signSwingLeft',
	esc_html__( 'Wiggle X', 'thememountain-plugin' ) => 'wiggleX',
	esc_html__( 'Wiggle Y', 'thememountain-plugin' ) => 'wiggleY',
	esc_html__( 'Drop in from bottom', 'thememountain-plugin' ) => 'dropUp',
	esc_html__( 'Drop in from top', 'thememountain-plugin' ) => 'dropDown',
	esc_html__( 'Roll in from left', 'thememountain-plugin' ) => 'rollInLeft',
	esc_html__( 'Roll in from right', 'thememountain-plugin' ) => 'rollInRight',
	esc_html__( 'Turn in from right', 'thememountain-plugin' ) => 'turnInRight',
	esc_html__( 'Turn in from left', 'thememountain-plugin' ) => 'turnInLeft',
	);

TM_Vc::$vc_elements_variable['rollover_animation'] = array(
	esc_html__( 'No animation effects', 'thememountain-plugin' ) => '',
	esc_html__( 'Overlay fade out', 'thememountain-plugin' ) => 'overlay-fade-out',
	esc_html__( 'Overlay fade in', 'thememountain-plugin' ) => 'overlay-fade-in',
	esc_html__( 'Image scale in', 'thememountain-plugin' ) => 'img-scale-in',
	esc_html__( 'Overlay fade img scale in', 'thememountain-plugin' ) => 'overlay-fade-img-scale-in',
	esc_html__( 'Overlay fade img scale out', 'thememountain-plugin' ) => 'overlay-fade-img-scale-out',
	esc_html__( 'Overlay slide in top', 'thememountain-plugin' ) => 'overlay-slide-in-top',
	esc_html__( 'Overlay slide in left', 'thememountain-plugin' ) => 'overlay-slide-in-left',
	esc_html__( 'Overlay slide in right', 'thememountain-plugin' ) => 'overlay-slide-in-right',
	esc_html__( 'Overlay slide in bottom', 'thememountain-plugin' ) => 'overlay-slide-in-bottom',
	esc_html__( 'Overlay img slide up', 'thememountain-plugin' ) => 'overlay-img-slide-up',
	esc_html__( 'Overlay img slide left', 'thememountain-plugin' ) => 'overlay-img-slide-left',
	esc_html__( 'Overlay img slide right', 'thememountain-plugin' ) => 'overlay-img-slide-right',
	esc_html__( 'Overlay img slide down', 'thememountain-plugin' ) => 'overlay-img-slide-down',
	esc_html__( 'Overlay / Image scale in', 'thememountain-plugin' ) => 'overlay-img-scale-in',
	);

TM_Vc::$vc_elements_variable['margin_notches'] = array(
	esc_html__( '-30', 'thememountain-plugin' ) => -30,
	esc_html__( '-20', 'thememountain-plugin' ) => -20,
	esc_html__( '-10', 'thememountain-plugin' ) => -10,
	esc_html__( '0', 'thememountain-plugin' ) => 0,
	esc_html__( '5', 'thememountain-plugin' ) => 5,
	esc_html__( '10', 'thememountain-plugin' ) => 10,
	esc_html__( '20', 'thememountain-plugin' ) => 20,
	esc_html__( '30', 'thememountain-plugin' ) => 30,
	esc_html__( '40', 'thememountain-plugin' ) => 40,
	esc_html__( '50', 'thememountain-plugin' ) => 50,
	esc_html__( '60', 'thememountain-plugin' ) => 60,
	esc_html__( '70', 'thememountain-plugin' ) => 70,
	esc_html__( '80', 'thememountain-plugin' ) => 80,
	esc_html__( '90', 'thememountain-plugin' ) => 90,
	esc_html__( '100', 'thememountain-plugin' ) => 100,
	esc_html__( '110', 'thememountain-plugin' ) => 110,
	esc_html__( '120', 'thememountain-plugin' ) => 120,
	esc_html__( '130', 'thememountain-plugin' ) => 130,
	esc_html__( '140', 'thememountain-plugin' ) => 140,
	esc_html__( '150', 'thememountain-plugin' ) => 150
	);

TM_Vc::$vc_elements_variable['spacing_notches'] = array(
	esc_html__( 'Inherit', 'thememountain-plugin' ) => 'inherit',
	esc_html__( '0', 'thememountain-plugin' ) => 0,
	esc_html__( '5', 'thememountain-plugin' ) => 5,
	esc_html__( '10', 'thememountain-plugin' ) => 10,
	esc_html__( '20', 'thememountain-plugin' ) => 20,
	esc_html__( '30', 'thememountain-plugin' ) => 30,
	esc_html__( '40', 'thememountain-plugin' ) => 40,
	esc_html__( '50', 'thememountain-plugin' ) => 50,
	esc_html__( '60', 'thememountain-plugin' ) => 60,
	esc_html__( '70', 'thememountain-plugin' ) => 70,
	esc_html__( '80', 'thememountain-plugin' ) => 80,
	esc_html__( '90', 'thememountain-plugin' ) => 90,
	esc_html__( '100', 'thememountain-plugin' ) => 100,
	esc_html__( '110', 'thememountain-plugin' ) => 110,
	esc_html__( '120', 'thememountain-plugin' ) => 120,
	esc_html__( '130', 'thememountain-plugin' ) => 130,
	esc_html__( '140', 'thememountain-plugin' ) => 140,
	esc_html__( '150', 'thememountain-plugin' ) => 150
	);

// column
TM_Vc::$vc_elements_variable['column_width'] = array(
	esc_html__('1 width', 'thememountain-plugin') => '1',
	esc_html__('2 width', 'thememountain-plugin') => '2',
	esc_html__('3 width', 'thememountain-plugin') => '3',
	esc_html__('4 width', 'thememountain-plugin') => '4',
	esc_html__('5 width', 'thememountain-plugin') => '5',
	esc_html__('6 width', 'thememountain-plugin') => '6',
	esc_html__('7 width', 'thememountain-plugin') => '7',
	esc_html__('8 width', 'thememountain-plugin') => '8',
	esc_html__('9 width', 'thememountain-plugin') => '9',
	esc_html__('10 width', 'thememountain-plugin') => '10',
	esc_html__('11 width', 'thememountain-plugin') => '11',
	esc_html__('12 width', 'thememountain-plugin') => '12',
	);
TM_Vc::$vc_elements_variable['column_offset'] = array(
	esc_html__('None', 'thememountain-plugin') => '',
	esc_html__('By 1 column', 'thememountain-plugin') => '1',
	esc_html__('By 2 columns', 'thememountain-plugin') => '2',
	esc_html__('By 3 columns', 'thememountain-plugin') => '3',
	esc_html__('By 4 columns', 'thememountain-plugin') => '4',
	esc_html__('By 5 columns', 'thememountain-plugin') => '5',
	esc_html__('By 6 columns', 'thememountain-plugin') => '6',
	esc_html__('By 7 columns', 'thememountain-plugin') => '7',
	esc_html__('By 8 columns', 'thememountain-plugin') => '8',
	esc_html__('By 9 columns', 'thememountain-plugin') => '9',
	esc_html__('By 10 columns', 'thememountain-plugin') => '10',
	esc_html__('By 11 columns', 'thememountain-plugin') => '11',
	);
TM_Vc::$vc_elements_variable['column_push'] = array(
	esc_html__('None', 'thememountain-plugin') => '',
	esc_html__('By 1 column', 'thememountain-plugin') => '1',
	esc_html__('By 2 columns', 'thememountain-plugin') => '2',
	esc_html__('By 3 columns', 'thememountain-plugin') => '3',
	esc_html__('By 4 columns', 'thememountain-plugin') => '4',
	esc_html__('By 5 columns', 'thememountain-plugin') => '5',
	esc_html__('By 6 columns', 'thememountain-plugin') => '6',
	esc_html__('By 7 columns', 'thememountain-plugin') => '7',
	esc_html__('By 8 columns', 'thememountain-plugin') => '8',
	esc_html__('By 9 columns', 'thememountain-plugin') => '9',
	esc_html__('By 10 columns', 'thememountain-plugin') => '10',
	esc_html__('By 11 columns', 'thememountain-plugin') => '11',
	);
TM_Vc::$vc_elements_variable['column_pull'] = array(
	esc_html__('None', 'thememountain-plugin') => '',
	esc_html__('By 1 column', 'thememountain-plugin') => '1',
	esc_html__('By 2 columns', 'thememountain-plugin') => '2',
	esc_html__('By 3 columns', 'thememountain-plugin') => '3',
	esc_html__('By 4 columns', 'thememountain-plugin') => '4',
	esc_html__('By 5 columns', 'thememountain-plugin') => '5',
	esc_html__('By 6 columns', 'thememountain-plugin') => '6',
	esc_html__('By 7 columns', 'thememountain-plugin') => '7',
	esc_html__('By 8 columns', 'thememountain-plugin') => '8',
	esc_html__('By 9 columns', 'thememountain-plugin') => '9',
	esc_html__('By 10 columns', 'thememountain-plugin') => '10',
	esc_html__('By 11 columns', 'thememountain-plugin') => '11',
	);

// avalanch slider
TM_Vc::$vc_elements_variable['slide_transition'] = array(
	esc_html__('Fade', 'thememountain-plugin') => 'fade',
	esc_html__('Slide Left Right', 'thememountain-plugin') => 'slideLeftRight',
	esc_html__('Slide Top Bottom', 'thememountain-plugin') => 'slideTopBottom',
	esc_html__('Scale In', 'thememountain-plugin') => 'scaleIn',
	esc_html__('Scale Out', 'thememountain-plugin') => 'scaleOut',
	);

// sizes
TM_Vc::$vc_elements_variable['sizes'] = array(
	esc_html__('Medium', 'thememountain-plugin') => 'medium',
	esc_html__('Small', 'thememountain-plugin') => 'small',
	esc_html__('Large', 'thememountain-plugin') => 'large',
	esc_html__('Xlarge', 'thememountain-plugin') => 'xlarge',
);

// SNS
TM_Vc::$vc_elements_variable['sns'] = array(
	esc_html__('None', 'thememountain-plugin') => null,
	esc_html__('500px', 'thememountain-plugin') => 'px',
	esc_html__('500px with circle', 'thememountain-plugin') => 'px-with-circle',
	esc_html__('Basecamp', 'thememountain-plugin') => 'basecamp',
	esc_html__('Behance', 'thememountain-plugin') => 'behance',
	esc_html__('Dribbble', 'thememountain-plugin') => 'dribbble',
	esc_html__('Dribbble with circle', 'thememountain-plugin') => 'dribbble-with-circle',
	esc_html__('Facebook', 'thememountain-plugin') => 'facebook',
	esc_html__('Facebook with circle', 'thememountain-plugin') => 'facebook-with-circle',
	esc_html__('Flickr', 'thememountain-plugin') => 'flickr',
	esc_html__('Flickr with circle', 'thememountain-plugin') => 'flickr-with-circle',
	esc_html__('GitHub', 'thememountain-plugin') => 'github',
	esc_html__('GitHub with circle', 'thememountain-plugin') => 'github-with-circle',
	esc_html__('Google', 'thememountain-plugin') => 'google',
	esc_html__('Google with circle', 'thememountain-plugin') => 'google-with-circle',
	esc_html__('Instagram', 'thememountain-plugin') => 'instagram',
	esc_html__('Instagram with circle', 'thememountain-plugin') => 'instagram-with-circle',
	esc_html__('LinkedIn', 'thememountain-plugin') => 'linkedin',
	esc_html__('LinkedIn with circle', 'thememountain-plugin') => 'linkedin-with-circle',
	esc_html__('Medium', 'thememountain-plugin') => 'medium',
	esc_html__('Medium with circle', 'thememountain-plugin') => 'medium-with-circle',
	esc_html__('Pinterest', 'thememountain-plugin') => 'pinterest',
	esc_html__('Pinterest with circle', 'thememountain-plugin') => 'pinterest-with-circle',
	esc_html__('Skype', 'thememountain-plugin') => 'skype',
	esc_html__('Skype with circle', 'thememountain-plugin') => 'skype-with-circle',
	esc_html__('Spotify', 'thememountain-plugin') => 'spotify',
	esc_html__('Spotify with circle', 'thememountain-plugin') => 'spotify-with-circle',
	esc_html__('StumbleUpon', 'thememountain-plugin') => 'stumbleupon',
	esc_html__('StumbleUpon with circle', 'thememountain-plugin') => 'stumbleupon-with-circle',
	esc_html__('Twitter', 'thememountain-plugin') => 'twitter',
	esc_html__('Twitter with circle', 'thememountain-plugin') => 'twitter-with-circle',
	esc_html__('Vimeo', 'thememountain-plugin') => 'vimeo',
	esc_html__('Vimeo with circle', 'thememountain-plugin') => 'vimeo-with-circle',
	esc_html__('Vine', 'thememountain-plugin') => 'vine',
	esc_html__('Vine with circle', 'thememountain-plugin') => 'vine-with-circle',
	esc_html__('Vk', 'thememountain-plugin') => 'vk',
	esc_html__('Vk with circle', 'thememountain-plugin') => 'vk-with-circle',
	esc_html__('Xing', 'thememountain-plugin') => 'xing',
	esc_html__('Xing with circle', 'thememountain-plugin') => 'xing-with-circle',
	esc_html__('Youko', 'thememountain-plugin') => 'youko',
	esc_html__('Youko with circle', 'thememountain-plugin') => 'youko-with-circle',
	esc_html__('YouTube', 'thememountain-plugin') => 'youtube',
	esc_html__('YouTube with circle', 'thememountain-plugin') => 'youtube-with-circle',
);
