<?php
/**
	tm_pricing_table_item.php
*/

// iconpicker custom icons
// https://wpbakery.atlassian.net/wiki/display/VC/Adding+Icons+to+vc_icon
if (class_exists( 'Vc_Manager' )) {
	vc_map( array(
		'name' => esc_html__( 'Pricing Table Column', 'thememountain-plugin' ),
		'category' => esc_html__( 'ThemeMountain', 'thememountain-plugin' ),
		'base' => 'tm_pricing_table_item',
		'icon' => 'icon-wpb-row',
		'show_settings_on_create' => true,
		'is_container' => true,
		'content_element' => false,
		'description' => '',
		'params' => array(
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Table Title', 'thememountain-plugin' ),
				'param_name' => 'title',
				'description' => esc_html__( 'Sets the column title.', 'thememountain-plugin' ),
				),
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Price', 'thememountain-plugin' ),
				'param_name' => 'table_price',
				'description' => esc_html__( 'Determines whether the pricing table should have a price section.', 'thememountain-plugin' ),
				),
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Currency', 'thememountain-plugin' ),
				'param_name' => 'table_currency',
				'description' => esc_html__( 'Determines whether a currency should be shown.', 'thememountain-plugin' ),
				),
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Interval', 'thememountain-plugin' ),
				'param_name' => 'table_interval',
				'description' => esc_html__( 'Determines whether the price is charged at an interval.', 'thememountain-plugin' ),
				),
			array(
				'type' => 'checkbox',
				'heading' => esc_html__( 'Show price line', 'thememountain-plugin' ),
				'param_name' => 'show_price_line',
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				'dependency' => array('element' => 'table_price','not_empty'=> TRUE),
				),
			array(
				'type' => 'checkbox',
				'heading' => esc_html__( 'Display interval on new line', 'thememountain-plugin' ),
				'param_name' => 'display_interval_on_new_line',
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Display Table Options As', 'thememountain-plugin' ),
				'param_name' => 'display_table_option_as',
				'value' => array(
					esc_html__( 'List', 'thememountain-plugin' ) => 'list',
					esc_html__( 'Text', 'thememountain-plugin' ) => 'text',
					),
				'std' => 'list',
				'description' => '',
				),
			array(
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use check icon for options', 'thememountain-plugin' ),
				'param_name' => 'icon_for_options',
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				'dependency' => array('element' => 'display_table_option_as','value'=>'list'),
				'description' => '',
				),
			array(
				"type" => "textarea_html",
				"holder" => "div",
				"heading" => esc_html__("Options", 'thememountain-plugin'),
				"param_name" => "content",
				"value" => '',
				'description' => esc_html__( 'This is where you list the table options as an unordered list or just as text.', 'thememountain-plugin' ),
				),
			ThemeMountain\TM_Vc::get_rich_text_editor_background_color_vc_field(),
			array(
				'type' => 'checkbox',
				'heading' => esc_html__( 'Callout', 'thememountain-plugin' ),
				'param_name' => 'is_callout',
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				'save_always' => true,
				'description' => esc_html__( "Wether the table should be highlighted. If selected, you will be able to set individual colors for the callout column.", 'thememountain-plugin' ),
				),
			array(
				'type' => 'checkbox',
				'heading' => esc_html__( 'Show column button', 'thememountain-plugin' ),
				'param_name' => 'show_column_button',
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				'save_always' => true,
				'description' => esc_html__( 'Wether the table should have a button.', 'thememountain-plugin' ),
				),
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Extra Class Name', 'thememountain-plugin' ),
				'param_name' => 'el_class',
				'description' => esc_html__( 'If you wish to style this component differently, then use the extra class name field to add one or several class names and then refer to it in your css file.', 'thememountain-plugin' )
				),

			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Table Column Footer Button Text', 'thememountain-plugin' ),
				'param_name' => 'table_footer_text',
				'dependency' => array('element' => 'show_column_button','value'=>'true'),
				'description' => '',
				),
			array(
				'type' => 'textfield',
				'heading' => esc_html__( 'Button Link URL', 'thememountain-plugin' ),
				'param_name' => 'link_url',
				'dependency' => array('element' => 'show_column_button','value'=>'true'),
				'description' => '',
				),
			array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Link target', 'thememountain-plugin' ),
				'param_name' => 'link_target',
				'value' => array(
					esc_html__( 'Same window', 'thememountain-plugin' ) => '_self',
					esc_html__( 'Blank', 'thememountain-plugin' ) => '_blank',
					esc_html__( 'New', 'thememountain-plugin' ) => '_new',
					),
				'std' => '_self',
				'save_always' => true,
				'dependency' => array('element' => 'show_column_button','value'=>'true'),
				'description' => '',
				),
			// array(
			// 	'type' => 'textfield',
			// 	'heading' => esc_html__( 'ID', 'thememountain-plugin' ),
			// 	'param_name' => 'el_id',
			// 	'value' => '',
			// 	),
			array(
				'type' => 'tab_id',
				'heading' => esc_html__( 'Table Column ID (internal use)', 'thememountain-plugin' ),
				'param_name' => "tab_id"
				),
			// design options
    		// Title Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Title Background Color', 'thememountain-plugin' ),
				'param_name' => 'title_background_color',
				'std' => '',
				'description' => '',
				),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use gradient for Title Background Color', 'thememountain-plugin' ),
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'param_name' => 'title_background_use_gradient',
				'std' => '',
				'description' => esc_html__( 'This will create a background image gradient, which means that if you have set an image as a background, the gradient will replace it. If selected, Background Color will be used as the start color for the gradient.', 'thememountain-plugin' ),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'End Title Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'title_background_gradient_end_color',
				'std' => '',
				'dependency' => array('element' => 'title_background_use_gradient','value'=>'true'),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Angle for the Title Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'title_background_gradient_angle',
				'description'=> esc_html__( 'Sets the angle of your gradient, acceptable values range from 0-360', 'thememountain-plugin' ),
				'dependency' => array('element' => 'title_background_use_gradient','value'=>'true'),
			),
			// End Title Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Title Font Color', 'thememountain-plugin' ),
				'param_name' => 'title_font_color',
				'std' => '',
				'description' => '',
				),
    		// Price Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Price Background Color', 'thememountain-plugin' ),
				'param_name' => 'price_background_color',
				'std' => '',
				'description' => '',
				),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use gradient for Price Background Color', 'thememountain-plugin' ),
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'param_name' => 'price_background_use_gradient',
				'std' => '',
				'description' => esc_html__( 'This will create a background image gradient, which means that if you have set an image as a background, the gradient will replace it. If selected, Background Color will be used as the start color for the gradient.', 'thememountain-plugin' ),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'End Price Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'price_background_gradient_end_color',
				'std' => '',
				'dependency' => array('element' => 'price_background_use_gradient','value'=>'true'),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Angle for the Price Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'price_background_gradient_angle',
				'description'=> esc_html__( 'Sets the angle of your gradient, acceptable values range from 0-360', 'thememountain-plugin' ),
				'dependency' => array('element' => 'price_background_use_gradient','value'=>'true'),
			),
			// End Price Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Price Font Color', 'thememountain-plugin' ),
				'param_name' => 'price_font_color',
				'std' => '',
				'description' => '',
				),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Price Line Color', 'thememountain-plugin' ),
				'param_name' => 'price_line_color',
				'std' => '#DDD',
				'description' => '',
				'dependency' => array('element' => 'show_price_line','value'=>'true'),
				),
    		// Options Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Options Background Color', 'thememountain-plugin' ),
				'param_name' => 'options_background_color',
				'std' => '',
				'description' => '',
				),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use gradient for Options Background Color', 'thememountain-plugin' ),
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'param_name' => 'options_background_use_gradient',
				'std' => '',
				'description' => esc_html__( 'This will create a background image gradient, which means that if you have set an image as a background, the gradient will replace it. If selected, Background Color will be used as the start color for the gradient.', 'thememountain-plugin' ),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'End Options Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'options_background_gradient_end_color',
				'std' => '',
				'dependency' => array('element' => 'options_background_use_gradient','value'=>'true'),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Angle for the Options Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'options_background_gradient_angle',
				'description'=> esc_html__( 'Sets the angle of your gradient, acceptable values range from 0-360', 'thememountain-plugin' ),
				'dependency' => array('element' => 'options_background_use_gradient','value'=>'true'),
			),
			// End Options Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Options Font Color', 'thememountain-plugin' ),
				'param_name' => 'options_font_color',
				'std' => '',
				'description' => '',
				),
    		// Footer Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Footer Background Color', 'thememountain-plugin' ),
				'param_name' => 'footer_background_color',
				'std' => '',
				'description' => '',
				),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use gradient for Footer Background Color', 'thememountain-plugin' ),
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'param_name' => 'footer_background_use_gradient',
				'std' => '',
				'description' => esc_html__( 'This will create a background image gradient, which means that if you have set an image as a background, the gradient will replace it. If selected, Background Color will be used as the start color for the gradient.', 'thememountain-plugin' ),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'End Footer Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'footer_background_gradient_end_color',
				'std' => '',
				'dependency' => array('element' => 'footer_background_use_gradient','value'=>'true'),
			),
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Angle for the Footer Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'footer_background_gradient_angle',
				'description'=> esc_html__( 'Sets the angle of your gradient, acceptable values range from 0-360', 'thememountain-plugin' ),
				'dependency' => array('element' => 'footer_background_use_gradient','value'=>'true'),
			),
			// End Footer Background color with gradient support
			array(
				'group' => esc_html__( 'Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Price Interval Opacity', 'thememountain-plugin' ),
				'param_name' => 'price_interval_opacity',
				'std' => '0.5',
				'description' => esc_html__( 'Determines the opacity of the pricing table interval, entered as a decimal from 0.1-1.', 'thememountain-plugin' ),
				),
			/**
			 * button
			 */
/*			array(
				'group' => 'Button Design Options',
				'type' => 'dropdown',
				'heading' => esc_html__( 'Icon Alignment', 'thememountain-plugin' ),
				'param_name' => 'icon_alignment',
				'value' => array(
					esc_html__( 'Icon Left', 'thememountain-plugin' ) => 'left',
					esc_html__( 'Icon Right', 'thememountain-plugin' ) => 'right',
				),
				'std' => 'left',
			),
*/
			array(
				'group' => 'Button Design Options',
				'type' => 'dropdown',
				'heading' => esc_html__( 'Button Size', 'thememountain-plugin' ),
				'param_name' => 'button_size',
				'value' => ThemeMountain\TM_Vc::$vc_elements_variable['sizes'],
				'std' => 'medium',
				'description' => esc_html__( 'Determines whether button should be small, medium, large or extra large in size.', 'thememountain-plugin' ),
			),
			array(
				'group' => 'Button Design Options',
				'type' => 'dropdown',
				'heading' => esc_html__( 'Button Style', 'thememountain-plugin' ),
				'param_name' => 'border_style',
				'value' => array(
					esc_html__( 'None', 'thememountain-plugin' ) => '',
					esc_html__( 'Rounded', 'thememountain-plugin' ) => 'rounded',
					esc_html__( 'Pill', 'thememountain-plugin' ) => 'pill',
				),
				'std' => '',
				'description' => esc_html__( 'Whether button should have sharp corners, rounded corners, or be pill shaped.', 'thememountain-plugin' ),
			),
    		// Button Background Color with gradient support
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Background Color', 'thememountain-plugin' ),
				'param_name' => 'button_bkg_color',
				'std' => '#EEE',
				'description' => '',
			),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'checkbox',
				'heading' => esc_html__( 'Use gradient for Button Background', 'thememountain-plugin' ),
				'value' => array( esc_html__( 'Yes', 'thememountain-plugin' ) => 'true' ),
				'param_name' => 'button_background_use_gradient',
				'std' => '',
				'description' => esc_html__( 'This will create a background image gradient, which means that if you have set an image as a background, the gradient will replace it. If selected, Background Color will be used as the start color for the gradient.', 'thememountain-plugin' ),
			),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'End Button Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'button_background_gradient_end_color',
				'std' => '',
				'dependency' => array('element' => 'button_background_use_gradient','value'=>'true'),
			),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'textfield',
				'heading' => esc_html__( 'Angle for the Button Background Color Gradient', 'thememountain-plugin' ),
				'param_name' => 'button_background_gradient_angle',
				'description'=> esc_html__( 'Sets the angle of your gradient, acceptable values range from 0-360', 'thememountain-plugin' ),
				'dependency' => array('element' => 'button_background_use_gradient','value'=>'true'),
			),
			// End Button background color with gradient support
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Background Color hover', 'thememountain-plugin' ),
				'param_name' => 'bkg_color_hover',
				'std' => '#D0D0D0',
				),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Border color', 'thememountain-plugin' ),
				'param_name' => 'border_color',
				'std' => '#EEE',
				),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Border color hover', 'thememountain-plugin' ),
				'param_name' => 'border_color_hover',
				'std' => '#D0D0D0',
				),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Label Color', 'thememountain-plugin' ),
				'param_name' => 'label_color',
				'std' => '#666',
				),
			array(
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'type' => 'colorpicker',
				'heading' => esc_html__( 'Button Label Color Hover', 'thememountain-plugin' ),
				'param_name' => 'label_color_hover',
				'std' => '#666',
				),
			// shadow checkbox
			array(
				'type' => 'checkbox',
				'group' => esc_html__( 'Button Design Options', 'thememountain-plugin' ),
				'heading' => esc_html__( 'Drop Shadow', 'thememountain-plugin' ),
				'param_name' => 'drop_shadow',
				'value' => array( esc_html__( 'Drop Shadow', 'thememountain-plugin' ) => 'true' ),
				'std' => '',
				'description' => '',
				),
			),
		'js_view' => 'TmTabView',
		) );
}

class WPBakeryShortCode_tm_pricing_table_item extends WPBakeryShortCode_tm_tab_item {
}